### ISSUE TITLE
no connect to server

### ISSUE THREAD

**Issue by Mannshoch** [nerzhul/ownCloud-SMS-App#106]
- hoster-server.com/cloud  (ssl signed) not work
- cloud.domain.com (selfsigned) not work
- cloud.domain.com/ over http instead https work.
### Server configuration

**ownCloud version:**  8.2.7

**PHP version:** 5.6
### Client configuration

**Android version:** 5.1

**Phone:** Fairphone

**ownCloud SMS app version:** 0.21.2

**Comment by nerzhul** [comment]
Hi @Mannshoch where did you download the application ?

**Comment by Mannshoch** [comment]
From the f-Droid App : [https://f-droid.org/repository/browse/?fdid=fr.unix_experience.owncloud_sms&fdpage=2](https://f-droid.org/repository/browse/?fdid=fr.unix_experience.owncloud_sms&fdpage=2)

**Comment by nerzhul** [comment]
F-Droid app is unofficial build and some things may not work especially on HTTPS. Please use google play store app

**Comment by Mannshoch** [comment]
I do not have google play configured anymore. It works for CalDAV and CardDAV over https and also the OwncloudClient works with https.

Interessting: 
If the Address is https I get in any way:
"Verbindung fehlgeschlagen, ist dies der richtige Server?" -> "Connection Error, is the server correct?"

if the Address is http I get a password error even it's correct.
If the Address is wrong (wrong character) i got the message: "UNK"

**Comment by nerzhul** [comment]
@Mannshoch i don't know which OwncloudClient is present in F-Droid app, but the client i'm using is quite old but working. I need to replace it at a moment

**Comment by Mannshoch** [comment]
It seems to be the same version like actual the actial released version [0.21.2](https://f-droid.org/wiki/page/fr.unix_experience.owncloud_sms). 

Is there maybe a special need for .htaccess entries? I had to remove many entries because my Hoster do not support them.

**Comment by nerzhul** [comment]
No you don't need special configuration outside of owncloud bare metal configuration. The only problem i see is the build done by F-Droid. Nobody on playstore mention your issue in comments :(

**Comment by erdoking** [comment]
I used the (paid ;) ) Playstore version 0.21.2 over ssl without any trouble ...

I delete data and uninstalled the official version. After that I installed the F-Droid version and write myself an test sms - works like a charm!

@Mannshoch: can you post any logs? logcat and/or apache logs? Please check also that your ssl-zertificat isn't broken ;)

**Comment by nerzhul** [comment]
as i remember the application doesn't support /owncloud at the end because server should be a host not and URL.
Maybe i can do some work to add final path to URI permitting to fix that

**Comment by keithzg** [comment]
Wait, so you're saying that if we don't have owncloud installed to the root of our webserver it won't work? That would explain my issues a moment ago when I tried out the app (installed via Google Play; I was honestly going to leave a negative review but then decided to seek out a github issues page instead).

**Comment by kbaegis** [comment]
Nextcloud/owncloud support this for sure. Your app doesn't?

**Comment by nerzhul** [comment]
@kbaegis owncloud and nextcloud are supported as i have the twice projects on my server to test it.
I should add a parameter to have a URL after the hostname to ensure the compat, if i get time i will patch it and send update to playstore this weekend

**Comment by nerzhul** [comment]
@kbaegis it support the twice app, but doesn't support having a path after the domain name, it's a different problem

**Comment by Mannshoch** [comment]
Owncloud SMS app from f-Droid : 0.22.2
Owncloud server: 8.2.7 (Update next spring to nextcloud  10)

CatLog:
OwncloudAuthenticator: Failed response while getting user information
OwncloudAuthenticator: ** statuscode: 401 ; response message: {"ocs":{"meta":{"status":"failure", "statuscode":997,"message":"Unauthorised"},"data":[]}}

Password is right for sure.

**Comment by nerzhul** [comment]
@Mannshoch 401 means wrong password, ocsms didn't sent any 401 itself

**Comment by Mannshoch** [comment]
It seems I have an other Problem. I detected that all Own/Nextcloud Apps On PC/Android work without Problem uploads and downloads work but if I try to share something from this app (share button) I got asked Username and Password and I got on all of them the feedback that the Password is wrong. On all user accounts.

SSL works on every phone unlike in Owncloud SMS.

**Comment by nerzhul** [comment]
There is no share support in owncloud SMS just sync. SSL doesn't work well with the non official F-Droid build, i didn't support it, sorry :)
