### ISSUE TITLE
Sync is not working

### ISSUE THREAD

**Issue by z4nD4R** [nerzhul/ownCloud-SMS-App#108]
### Steps to reproduce
1. Upgrade cloud to 9.0.4
2. Upgrade ocsm on cloud 1.4.1 - 1.7.0
3. Should be enough
### Expected behaviour

Sms are synced up
### Actual behaviour

Can not sync sms. I bought new S6 phone. Installed Owncloud-SMS and sms are not being synced although my sms from telephone were synced to cloud. But from cloud - phone not.
There is some other strange behaviour. 
1. After I marked some message as read after I access the sms page again all messages apperead as unreaded 
2. Some conversation are listen twice, as numner and as contact name. When I click on number after a while it will load the contact properly (with name and all sms) but after f5-ing remain the same
3. In app My Accounts -> {account} -> I got error
   - Contact list:
     "Server doesn't support this feature. Ensure sever is running at least version 1.6"
   - Contact information:
     "contact phones"

But the main issue is: Sms are not synced from cloud -> phone
### Server configuration

**ownCloud version:** 
9.0.4

**PHP version:**
php5

**HTTPd server:**
apache2
**HTTPS:**
YES
### Client configuration

**Android version:**
6.0.1 - permission given to the app

**Phone:**
Galaxy S6

**ownCloud SMS app version:**
0.21.2
### Logs

Eventhough I have set up logleve = 0, there is no relevent log :( in owncloud.log

```
[31/Aug/2016:21:36:54 +0200] "GET /cloud/index.php/apps/ocsms/get/apiversion?format=json HTTP/1.1" 200 5444 "-" "Jakarta Commons-HttpClient/3.1" => return {"version" : 1 }

[31/Aug/2016:21:36:54 +0200] "GET /cloud/index.php/apps/ocsms/get/smsidlist?format=json HTTP/1.1" 200 1060 "-" "Jakarta Commons-HttpClient/3.1" => return {"smslist":[]}
[31/Aug/2016:21:36:55 +0200] "POST /cloud/index.php/apps/ocsms/push?format=json HTTP/1.1" 200 1072 "-" "Jakarta Commons-HttpClient/3.1"

```

**Comment by FabulousPhil** [comment]
I'm having the same problem. 
Android: 5.1.1
Phone: Kogan Agora 4G Pro
Owncloud SMS on phone: 0.21.2
Owncloud SMS on server: 1.7.0
Owncloud: 8.1.9
This is really quite annoying and makes it near useless.

**Comment by nerzhul** [comment]
@z4nD4R it was an accidentally released feature. It was removed in master but i didn't publish the new version yet. I think i will publish the bugfix version soon
