### ISSUE TITLE
Sent and Recieved Appear in Different Converstions/Threads

### ISSUE THREAD

**Issue by d0n601** [nerzhul/ownCloud-SMS-App#114]
### Steps to reproduce
1. Installed OwnCloud Server with Contacts App
2. Set contact phone numbers. Phone numbers are input including country code +18085551234
3. Sync phone numbers via CardDav and sync SMS via app

### Expected behaviour
SMS messages appear  in threads according to contact settings. Sent messages, and messages received should appear in the same thread.

### Actual behaviour
SMS messages sent to me appear in a thread with my contact's name, with their number below it, including the country code +18085551234. SMS messages that I send to the same contact appear in a separate thread with their phone number, excluding the country code 8085551234. I've tried adding and removing the country code from my contact, and doing this inverts the behaviour I've described above, and then sent messages have my contacts name, and messages received display in a separate thread with their phone number.

How can I combine these threads into one conversation? 

### Server configuration

**ownCloud version:** 
9.1.1

**PHP version:**
7.0

**HTTPd server:**
apache

**HTTPS:**
LetsEncrypt

### Client configuration

**Android version:**
CyanogenMod 13

**Phone:**
Nexus 5

**ownCloud SMS app version:**
0.22.2

**Comment by nerzhul** [comment]
Hi, thanks for the report, but this issue is already set in the backend repo (https://github.com/nerzhul/ocsms)
