### ISSUE TITLE
Move to Nextcloud

### ISSUE THREAD

**Issue by stefan-niedermann** [nerzhul/ownCloud-SMS-App#116]
Since all major apps (mail, contacts, notes, news) moved to Nextcloud: Do you have any plans to move to Nextcloud as primary platform?
If yes: I would be able to provide a pull request with new theme-colors and icons if you wish.

**Comment by nerzhul** [comment]
Hello @stefan-niedermann .
In fact we are already present on the two sides:

https://apps.nextcloud.com/apps/ocsms

Please look at the ocsms repo, this file: https://github.com/nerzhul/ocsms/blob/master/appinfo/info.xml

**Comment by nerzhul** [comment]
If yo uwant to contribute, theming could be good on android
