### ISSUE TITLE
error #9: server set unhandled http ret

### ISSUE THREAD

**Issue by lepidas** [nerzhul/ownCloud-SMS-App#117]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen
sync sms
### Actual behaviour
Tell us what happens instead
sms not syncing
error #9: server set unhandled http ret
### Server configuration

**ownCloud version:** 
10.0.1
**PHP version:**
7.0.8
**HTTPd server:**
apache
**HTTPS:**
yes
### Client configuration

**Android version:**
6
**Phone:**
huawei p8lite
**ownCloud SMS app version:**

### Logs

```
Insert your log here
```
error #9: server set unhandled http ret

**Comment by nerzhul** [comment]
you are not very precise, error 9 means return code is unhandled, ensure your servers works or provide owncloud/nextcloud logs

**Comment by lepidas** [comment]
Exception: {"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'INSERT INTO oc_ocsms_smsdatas (user_id, added, lastmodified, sms_flags, sms_date, sms_id,sms_address, sms_msg, sms_mailbox, sms_type) VALUES (?,?,?,?,?,?,?,?,?,?)' with params [\"myusername\", \"2016-12-13 18:35:23\", \"2016-12-13 18:35:23\", \"11\", \"1481560356410\", 611, \"+47xxxxxxxx\", \"Great, I will be back from work about five tomorrow. \\nHave a Nice evening\\ud83d\\ude0a\", 0, 1]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x8A' for column 'sms_msg' at row 1","Code":0,"Trace":"#0 \/var\/www\/nextcloud\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/nextcloud\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(174): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO oc_...', Array)\n#2 \/var\/www\/nextcloud\/html\/lib\/private\/legacy\/db\/statementwrapper.php(74): Doctrine\\DBAL\\Statement->execute(Array)\n#3 \/var\/www\/nextcloud\/html\/apps\/ocsms\/db\/smsmapper.php(289): OC_DB_StatementWrapper->execute(Array)\n#4 \/var\/www\/nextcloud\/html\/apps\/ocsms\/controller\/apicontroller.php(82): OCA\\OcSms\\Db\\SmsMapper->writeToDB('blades', Array)\n#5 [internal function]: OCA\\OcSms\\Controller\\ApiController->push(543, Array)\n#6 \/var\/www\/nextcloud\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#7 \/var\/www\/nextcloud\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\OcSms\\Controller\\ApiController), 'push')\n#8 \/var\/www\/nextcloud\/html\/lib\/private\/AppFramework\/App.php(111): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\OcSms\\Controller\\ApiController), 'push')\n#9 \/var\/www\/nextcloud\/html\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('ApiController', 'push', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#10 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#11 \/var\/www\/nextcloud\/html\/lib\/private\/Route\/Router.php(293): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#12 \/var\/www\/nextcloud\/html\/lib\/base.php(983): OC\\Route\\Router->match('\/apps\/ocsms\/pus...')\n#13 \/var\/www\/nextcloud\/html\/index.php(48): OC::handleRequest()\n#14 {main}","File":"\/var\/www\/nextcloud\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":116}

**Comment by lepidas** [comment]
Iam not sure it's a server side or android app problem though.

**Comment by nerzhul** [comment]
This is a serverside issue, you have an encoding problem shown in this message

General error: 1366 Incorrect string value: '\xF0\x9F\x98\x8A' for column 'sms_msg' at row 1"
