### ISSUE TITLE
"Unable to perform a HTTP connection" when connecting to https server with Let's Encrypt certificate on Android 4.4

### ISSUE THREAD

**Issue by cptMikky** [nerzhul/ownCloud-SMS-App#129]
### Steps to reproduce
1. Have ownCloud installation on a server with a Let's Encrypt certificate
2. Install app on Android KitKat (CM11 in my case)
3. Try to create an account in App via https
4. "Unable to perform a HTTP connection"

### Expected behaviour
App connects and creates an android account

### Actual behaviour
"Unable to perform a HTTP connection"

### Server configuration

**ownCloud version: 8.2** 

**PHP version: 5.6**

**HTTPd server: Apache 2.4**

**HTTPS: Yes, using valid Let's Encrypt cert**

### Client configuration

**Android version: 4.4 (CyanogenMod 11)**

**Phone: Motorola Defy+ (but this is irrelevant)**

**ownCloud SMS app version: 0.23.2 from F-Droid**

### Logs

No logs obtained.

### Additional info
The problem is most likely related to the SSL/TLS part as if I choose plain http, app connects without any problems. This works on Android 6.

**Comment by nerzhul** [comment]
Can you provide logcat logs and re-test with 0.24.0 at least ?

**Comment by jtal7** [comment]
I believe to have a similar problem: Upon trying to set up NextcloudSMS account on phone and "sign in" the error message is displayed as above 
_"Unable to perform a HTTP connection. Please ensure there is a web server"._ 
This happens although a https (and not http) connection was requested.

**Server**: Linux, Apache 2.4.25, MariaDB 10.0.29, PHP 5.6.30 running at home
owncloud-9.1.4 with a self-signed certificate, using OwnCloudSMS-1.11.4
server-side owncloud is only configured for https on port 443, no http configured, and firewall would reject port 80 connections anyway. The NAT is only configured for port 443

**Client:** CyanogenMod 14.1-20161220-Nightly
Nextcloud SMS 0.24.1
Self-signed root-certificate was successfully imported
ownCloud client 2.2.0 and DAVdroid 1.4.0.2-ose successfully connect to and sync with my above server using https based on my self-signed certificate (as does e.g. chromium).

**LOGS:** Upon trying to set up the NextcloudSMS account with login-credentials and pressing the "SIGN IN" button (after having cleared the logs), the only thing I got out of aLogcat (no experience with this program) is:
_"--------beginning of main
finishComposingText on inactive InputConnection"_

**REMARKS:**
The whole setup including ocSMS worked earlier, it may have failed after upgrade of phone to CyanogenMod equivalent of Android 6 or 7. Another phone in a similar situation displayed error message: 
_"OcSMS: Fatal error !
Error #13: Unable to perform a connection"_
Again, this might well have started after CyanogenMod upgrade to Nougat. 
How can I help?

**Comment by Cosmostrix** [comment]
I have the same issue.

**NGINX LOG:**
SSL_do_handshake() failed (SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking

**LOGCAT:**
fr.unix_experience.owncloud_sms.activities.LoginActivity.UserLoginTask: Failed to login, IOException occured: Certificate expired at Mon Feb 01 23:50:55 JST 2016 (compared to Sat Feb 25 01:29:47 JST 2017)

It seems client certificate has expired, maybe.

**Comment by cptMikky** [comment]
I'll have to check logs as well but I don't use any client certificate so this is either a different problem or the cause is somewhere else. 

I wasn't able to test it further since I lost the "old" phone with KitKat and it works with Android 6 on Xperia Z5 so I presume it may have something to do with Let's Encrypt certificates not being trusted by KitKat.

**Comment by Cosmostrix** [comment]
I use Android 5 but experiencing the issue. I checked standard browser and system CAs so I can say Let's Encrypt certificates are trusted.

**Comment by oldnomad** [comment]
For me the problem occurs with Nextcloud SMS version 1.0.0. Logcat was weird: it said that certificate expired on Apr 02 02:59:59 GMT+03:00 2017; however, my Let's Encrypt certificate was _issued_ on 01 Apr 2017 23:17:00 UTC.

After checking the NC instance with Qualys SSL checker, I found that it actually returns _two_ certificate chains: valid Let's Encrypt certificate that I've installed, and an expired wildcard certificate installed by my hosting provider. If I read the RFC correctly, only the first certificate chain should be checked.

Nextcloud app, OCReader, and some other apps have no problems with that situation, but Nextcloud SMS fails, so I guess it does something differently.

**Comment by nerzhul** [comment]
hi @oldnomad,
i don't really know why you are blocked. We are using a standard Android SSL connection method, maybe we are less lazy than other apps ? You should not return 2 certificates, i don't know how this is possible.

**Comment by oldnomad** [comment]
After some experiments I can finally tell what is happening in my case.

My hosting provider has a wildcard certificate for all his subdomains, which expired. For my subdomain I've installed a Let's Encrypt certificate, which is valid. However, valid certificate is returned only if the client uses SNI (seems logical, SNI is the only way to know the host name at TLS handshake stage). I suppose that the method that Nextcloud SMS uses (EasySSLProtocolSocketFactory) doesn't support SNI.

**Comment by nerzhul** [comment]
Oh our client doesn't support SNI it's a real problem. But my nginx has multiple certificates and it works... Hmm

**Comment by oldnomad** [comment]
Several certificates aren't a problem, at least without pinning. The problem occurs only when the "generic" certificate (returned without SNI) is invalid.

**Comment by nerzhul** [comment]
okay then you should handle if possible the "generic" certificate, i cannot make it less secure :(

**Comment by db260179** [comment]
Possible you have the same issue as me
https://github.com/nerzhul/ownCloud-SMS-App/issues/151

Check what SSL protocols you are using, this app seems to want TLSv1 or older to connect.

**Comment by nerzhul** [comment]
fixed by ceba0324e1ae92ac4edd2104cb4736d7f8706902
