### ISSUE TITLE
Sync old messages

### ISSUE THREAD

**Issue by adamlove86** [nerzhul/ownCloud-SMS-App#131]
Would love to be able to sync my old messages as a backup - perhaps it wouldn't be too hard for the app to slowly go through and back up/sync my old messages over time?

I'm running Nextcloud 11, Ubuntu, Nextcloud SMS 1.11.4

Have been asked to reopen issue in this repo
https://github.com/nextcloud/ocsms/issues/156

Thanks in advance and if there's anything else I can help with, please let me know.

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**ownCloud version:** 

**PHP version:**

**HTTPd server:**

**HTTPS:**

### Client configuration

**Android version:**

**Phone:**

**ownCloud SMS app version:**

### Logs

```
Insert your log here
```

**Comment by jonlachmann** [comment]
Just wanted to say I would LOVE this feature, then I can finally give up Mightytext and be self-reliant!

Great app still!

**Comment by nerzhul** [comment]
Mightytext ?

**Comment by jonlachmann** [comment]
https://mightytext.net/ it is like imessage for android, but rather expensive if you want the pro edition

**Comment by adamlove86** [comment]
Agree! I've had Mightytext for two years but the Chrome Extension freezes my computer... Seems to take up a hideous amount of RAM. Refusing to pay for a third year because it hasn't been fixed - and considering how much it costs.... =/

**Comment by nerzhul** [comment]
@adamlove86 sorry for to be late here, a recent update added resetting synchronization cursor position in Android app, permitting to resync old messages, does that fit to you ?

**Comment by harpogit** [comment]
Hello, Nerzhul,
I finally have a synchro between my nextcloud server on La Brique and an android 6;01 Samsung, but I only get one message ! The last one. How could I sync the older one?
The resetting synchronization cursor process seems not to change anything.

Thank you !

**Comment by nerzhul** [comment]
@harpogit i should re-verify it should not be the case

**Comment by nerzhul** [comment]
Hello, thanks for your reports, i took some time to look at this and the full sync + reset cursor problem was (in major part) to wrong sms ordering when reading from sms database.

I'm publishing 1.2.3 to play store now, i tested it on my phone and it seems some missed old messages appears when re-doing a full sync with cursor reset.

Fixed by 3edd898d7dff73c32ad6dfbafed70e84134e4f56

**Comment by harpogit** [comment]
Super!
Thanks a lot ! I wish I could actually use it !
Just waiting until I find the update on FDroid.
;-)

**Comment by harpogit** [comment]
...I just upgrade Nextcloud on my Brique, then I lost the only miraculous sms I got last time !
It's a real thrill, isn'it?
;-)

**Comment by pciavald** [comment]
I have the same issue, i see someone else is having it here: https://github.com/nextcloud/ocsms/issues/156#issuecomment-508917992

i had the synchro activated back in 2015 and now i reactivated it on my new phone, i'd like to sync all messages from this phone but only the newly pushed-on-receive messages show up in nextcloud. I've reset the cursor and resynced but it just says synchro complete without adding the messages between 2015 and now
