### ISSUE TITLE
Unable to sync messages if emoji/emoticons in them

### ISSUE THREAD

**Issue by dienteperro** [nerzhul/ownCloud-SMS-App#135]
### Steps to reproduce
1. Send or receive a sms with some emoji/emoticons in them.
2. After some tries Nextcloud SMS client will report: Nextcloud SMS: Fatal error! Error #9: Server set unhandled HTTP return code
3. The thread with the emoji symbols will not sync.
4. Delete the sms with the emoji in it and Nextcloud SMS client will sync fine again.

### Expected behaviour
Nextcloud SMS should sync SMSs with or without emoji / emoticons in them just fine. Perhaps it should replace the symbols, place a token character in them, or use an external linked library with the same/similar graphical symbols.

### Actual behaviour
Nextcloud SMS fails to sync threads with SMSs with emoji symbols in them.

### Server configuration

**ownCloud version:** Nextcloud 11.0.1 (stable) / Owncloud 9.1

**PHP version:** 7.0.13

**HTTPd server:** Apache 2.4.18-2ubuntu3.1

**HTTPS:** Apache 2.4.18-2ubuntu3.1 + self signed certificate

### Client configuration

**Android version:** 4.4.2

**Phone:** Huawei Hol-U19

**ownCloud SMS app version:** 0.24.1

### Logs

```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO oc_ocsms_smsdatas (user_id, added, lastmodified, sms_flags, sms_date, sms_id,sms_address, sms_msg, sms_mailbox, sms_type) VALUES (?,?,?,?,?,?,?,?,?,?)' with params ["user", "2017-01-23 21:22:03", "2017-01-23 21:22:03", "11", "1485124282764", 910, "+5352427295", "\ud83c\udf0b\ud83c\udf7b\ud83c\udf7b\ud83c\udf7b\ud83c\udf7b\ud83c\udf77\ud83c\udf77\ud83c\udf77", 0, 1]: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x8C\x8B\xF0\x9F...' for column 'sms_msg' at row 1
```

**Comment by enoch85** [comment]
Could be utf8mb4 related.

**Comment by enoch85** [comment]
https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by nerzhul** [comment]
I looked at the whole nextcloud source code to understand how this can be fixed.

Please add 'mysql.utf8mb4' => true, to your config.php

See: https://github.com/nextcloud/server/blob/33ca69166a41188a6e19849243c5e1c2a16860dc/config/config.sample.php#L1243

You may need to alter your MySQL tables after this, like mentioned in @enoch85 article:

```
ALTER TABLE table_name CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

Or just use a real SQL engine, pgsql (_joke_)

**Comment by nerzhul** [comment]
Also please note this issue is purely server side and should be opened in https://github.com/nextcloud/ocsms

**Comment by enoch85** [comment]
Small guide: https://github.com/nextcloud/vm/issues/97#issuecomment-273812862

**Comment by dienteperro** [comment]
After all not really an issue! I found in the documentation the correct setup for server in order to support emoji! Sorry
