### ISSUE TITLE
Activate translations on Transifex

### ISSUE THREAD

**Issue by enoch85** [nerzhul/ownCloud-SMS-App#139]
Now when https://github.com/nextcloud/ocsms/issues/166 is merged, we should activate this on the client side as well. 

@MorrisJobke Here is the ticket. ;) Does @nerzhul need to do anything? There are already manual translations here: https://github.com/nerzhul/ownCloud-SMS-App/tree/master/src/main/res

**Comment by MorrisJobke** [comment]
> @MorrisJobke Here is the ticket. ;) Does @nerzhul need to do anything? There are already manual translations here: https://github.com/nerzhul/ownCloud-SMS-App/tree/master/src/main/res

Yes - @nextcloud-bot needs to be added as collaborator to this repo ;)

**Comment by enoch85** [comment]
@nerzhul --^ Please

**Comment by enoch85** [comment]
ping @nerzhul

**Comment by nerzhul** [comment]
@enoch85 done, but i don't see how to intergrate it properly without breaking current app

**Comment by nerzhul** [comment]
how translations work on server side app ? i see some JS files are now included, but how can i integrate them efficiently ?

**Comment by enoch85** [comment]
@MorrisJobke --^

@nerzhul I don't know how this works actually.

**Comment by MorrisJobke** [comment]
> @enoch85 done, but i don't see how to intergrate it properly without breaking current app

Just leave everything as it is. I will setup the "Android" style of translation files (as they are in that way already). So you should have no overhead here.

**Comment by MorrisJobke** [comment]
And it runs. Every night at roughly 2 am UTC it runs and updates the translations from transifex. It pushes new english versions and fetches new translations from transifex. So if you edit the translation in this repo directly they will be overwritten. You need to do the change on transifex.

https://github.com/nerzhul/ownCloud-SMS-App/commit/c9c2701355047d2153d0fe938a9fa7b87b4eaac4

https://www.transifex.com/nextcloud/nextcloud/android-sms/
https://www.transifex.com/nextcloud/nextcloud/android-sms-playstore/

**Comment by enoch85** [comment]
Great, it works! Thanks @MorrisJobke 

Thoug one strange thing, it seems it catches strings as well:
![screenshot from 2017-02-03 20-17-59](https://cloud.githubusercontent.com/assets/4511254/22604900/e10cfede-ea4d-11e6-92e4-2f2b3bdff171.png)

**Comment by enoch85** [comment]
Issue solved anyway, so closing. Still waiting for answers on ---^ though @MorrisJobke

**Comment by MorrisJobke** [comment]
> Though one strange thing, it seems it catches strings as well:

That's how it is listed as english source string: https://github.com/nerzhul/ownCloud-SMS-App/blob/32475e72e6533a68b4ba3740f4889130233c76c7/src/main/res/values/strings.xml#L37

Just fix the english version and it will get updated on transifex automatically ;)

**Comment by enoch85** [comment]
Aah, don't know how, but I'll have a look. :+1:

**Comment by enoch85** [comment]
Aaah ok, so everything with `<string name=` is fetched I guess.... @nerzhul Could those be removed or renamed?

**Comment by nerzhul** [comment]
no, account_type cannot move outside of this at this moment without breaking application, this needs testing on app

**Comment by enoch85** [comment]
@nerzhul What about https://github.com/nerzhul/ownCloud-SMS-App/blob/32475e72e6533a68b4ba3740f4889130233c76c7/src/main/res/values/strings.xml#L33-L45 Any of them?

**Comment by AndyScherzinger** [comment]
Hi @enoch85 @nerzhul 
I can be moved (see Nextcloud Android app source) or at least be marked as not to be translated (there is an attribute for it). You can also just open an issue and assign it to me and I'll to the move 🚀
