### ISSUE TITLE
SMS doesn't get synced on Android 7.1.1

### ISSUE THREAD

**Issue by enoch85** [nerzhul/ownCloud-SMS-App#141]
### Steps to reproduce
1. Activate Nextcloud SMS on Nextcloud App store
2. Download ownCloud SMS from Plat store
3. Configure the apps
4. Sync

### Expected behaviour
SMS should show up in the App on Nextcloud

### Actual behaviour
The Android client syncs without any issues, but no messages show up in the Nextcloud App. Permissions error in Android 7.1.1? I allowed it to access both SMS and Contacts:
![screenshot_20170203-204704](https://cloud.githubusercontent.com/assets/4511254/22605873/12fcf7ec-ea52-11e6-84af-10185cb45004.png)

### Server configuration
**Nextcloud version:** 
11.0.1
**PHP version:**
7.0
**HTTPd server:**
Apache 2.4
**HTTPS:**
Yes
### Client configuration
**Android version:**
7.1.1
**Phone:**
LG Google Nexus 5x
**Nextcloud SMS app version:**
0.24.3
### Logs

```
No logs
```

**Comment by nerzhul** [comment]
Can you look at logcat logs and your http daemon access logs ? without this it's too vague

**Comment by enoch85** [comment]
logcat? https deamon?

**Comment by nerzhul** [comment]
logcat is android syslog like, you can have a frontend installing some apps, or on your computer, you can filter per application

**Comment by enoch85** [comment]
Sorry, I have no clue what you are taking about. Do I need to install the Android SDK for this, or can I find the logcat on my server? Or is it a Chrome log?

**Comment by nerzhul** [comment]
logcat is purely android side, you have some android apps for this, or you can use adb from android sdk.

For the server side only access logs on your http server (apache or nginx) are sufficient

**Comment by enoch85** [comment]
Can't find anything in my server logs, and it seems I need a rooted phone to access logcat. 

But, I noticed when I sync it shows an error, but there is no time to read it as it only shows for like 3 ms.

**Comment by enoch85** [comment]
Where do I find the recent log messages on the phone? Where are errors logged in the server? As loglevel 4 in Nextcloud log?

**Comment by nerzhul** [comment]
@enoch85 i think just enabling developper mode on your phone can help.

For server errors, in nextcloud errors if fatal, else look at your apache access logs

**Comment by enoch85** [comment]
Activated developer mode but can't grant access to logcat.
![screenshot_20170203-232602](https://cloud.githubusercontent.com/assets/4511254/22611012/ad406148-ea68-11e6-9a90-1cf73b2b6759.png)

No fatal error in the log for ocsms...

**Comment by devz3r0** [comment]
Hi, 
I got you app too, and have the same issue with my 7.1.1 device but I have rooted it and filtered the OCC part out:

`02-04 11:29:53.513 I/OCSMSOwnCloudClient(9720): HTTP Request done at try 1
02-04 11:29:53.571 E/OCSMSOwnCloudClient(9720): Server set unhandled HTTP return code 500
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): Status code: 500. Response message: <!DOCTYPE html>
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): <html class="ng-csp" data-placeholder-focus="false" lang="en" >
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 	<head data-requesttoken="">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 		<meta charset="utf-8">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 		<title>
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 		Nextcloud		</title>
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 		<meta http-equiv="X-UA-Compatible" content="IE=edge">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 		<meta name="referrer" content="never">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 		<meta name="apple-itunes-app" content="app-id=1125420102">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 		<meta name="theme-color" content="#0082c9">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 		<link rel="icon" href="/core/img/favicon.ico">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 		<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#1d2d44">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/vendor/select2/select2.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/styles.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/header.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/icons.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/fonts.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/apps.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/global.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/fixes.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/multiselect.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/mobile.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/jquery-ui-fixes.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/tooltip.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/share.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/apps/files_versions/css/versions.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/apps/files_pdfviewer/css/style.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/apps/files_videoplayer/css/style.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/inputs.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/jquery.ocdialog.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/styles.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/header.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 											<script nonce="WnRWMll3ODc1cEhUOVRFMEIyWmVsd2FkZXRTN3ZoUTdOWmVXazNyby9nTT06QTVvNUxFMTJyY0RtdjBzZmNsSTcrelg2UDYzZjdTUmZVS1B3M2tyZnJYWT0=" src="/core/vendor/jquery/dist/jquery.min.js?v=738b385f38fa5473bc1770addb3de088"></script>
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<script nonce="WnRWMll3ODc1cEhUOVRFMEIyWmVsd2FkZXRTN3ZoUTdOWmVXazNyby9nTT06QTVvNUxFMTJyY0RtdjBzZmNsSTcrelg2UDYzZjdTUmZVS1B3M2tyZnJYWT0=" src="/core/vendor/jquery-migrate/jquery-migrate.min.js?v=738b385f38fa5473bc1770addb3de088"></script>
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<script nonce="WnRWMll3ODc1cEhUOVRFMEIyWmVsd2FkZXRTN3ZoUTdOWmVXazNyby9nTT06QTVvNUxFMTJyY0RtdjBzZmNsSTcrelg2UDYzZjdTUmZVS1B3M2tyZnJYWT0=" src="/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=738b385f38fa5473bc1770addb3de088"></script>
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<script nonce="WnRWMll3ODc1cEhUOVRFMEIyWmVsd2FkZXRTN3ZoUTdOWmVXazNyby9nTT06QTVvNUxFMTJyY0RtdjBzZmNsSTcrelg2UDYzZjdTUmZVS1B3M2tyZnJYWT0=" src="/core/vendor/underscore/underscore.js?v=738b385f38fa5473bc1770addb3de088"></script>
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<script nonce="WnRWMll3ODc1cEhUOVRFMEIyWmVsd2FkZXRTN3ZoUTdOWmVXazNyby9nTT06QTVvNUxFMTJyY0RtdjBzZmNsSTcrelg2UDYzZjdTUmZVS1B3M2tyZnJYWT0=" src="/core/vendor/moment/min/moment-with-locales.js?v=738b385f38fa5473bc1770addb3de088"></script>
02-04 11:29:53.572 E/OCSMSOwnCloudClient(9720): 					<script nonce="WnRWMll3ODc1cEhUOVRFMEIyWmVsd2FkZXRTN3ZoUTdOWmVXazNyby9nTT06QTVvNUxFMTJyY0RtdjBzZmN
02-04 11:29:56.177 I/OCSMSOwnCloudClient(9720): HTTP Request done at try 1
02-04 11:29:56.234 E/OCSMSOwnCloudClient(9720): Server set unhandled HTTP return code 500
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): Status code: 500. Response message: <!DOCTYPE html>
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): <html class="ng-csp" data-placeholder-focus="false" lang="en" >
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 	<head data-requesttoken="">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 		<meta charset="utf-8">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 		<title>
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 		Nextcloud		</title>
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 		<meta http-equiv="X-UA-Compatible" content="IE=edge">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 		<meta name="referrer" content="never">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 		<meta name="apple-itunes-app" content="app-id=1125420102">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 		<meta name="theme-color" content="#0082c9">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 		<link rel="icon" href="/core/img/favicon.ico">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 		<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#1d2d44">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/vendor/select2/select2.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/styles.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/header.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/icons.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/fonts.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/apps.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/global.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/fixes.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/multiselect.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/mobile.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/jquery-ui-fixes.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/tooltip.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/share.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/apps/files_versions/css/versions.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/apps/files_pdfviewer/css/style.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/apps/files_videoplayer/css/style.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/inputs.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/jquery.ocdialog.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/styles.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<link rel="stylesheet" href="/core/css/header.css?v=738b385f38fa5473bc1770addb3de088">
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 											<script nonce="Nit5T0NzaGpXNVg4N2NhbHcydXgzYWdITUdHVjQ2eWp4d3FMLzNDcDFmVT06M0tQRlBaSUFGc3kxMWFuZHB4K0p0LzV5YWxmaG1jbnh0VXZoczBQUW1ZMD0=" src="/core/vendor/jquery/dist/jquery.min.js?v=738b385f38fa5473bc1770addb3de088"></script>
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<script nonce="Nit5T0NzaGpXNVg4N2NhbHcydXgzYWdITUdHVjQ2eWp4d3FMLzNDcDFmVT06M0tQRlBaSUFGc3kxMWFuZHB4K0p0LzV5YWxmaG1jbnh0VXZoczBQUW1ZMD0=" src="/core/vendor/jquery-migrate/jquery-migrate.min.js?v=738b385f38fa5473bc1770addb3de088"></script>
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<script nonce="Nit5T0NzaGpXNVg4N2NhbHcydXgzYWdITUdHVjQ2eWp4d3FMLzNDcDFmVT06M0tQRlBaSUFGc3kxMWFuZHB4K0p0LzV5YWxmaG1jbnh0VXZoczBQUW1ZMD0=" src="/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=738b385f38fa5473bc1770addb3de088"></script>
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<script nonce="Nit5T0NzaGpXNVg4N2NhbHcydXgzYWdITUdHVjQ2eWp4d3FMLzNDcDFmVT06M0tQRlBaSUFGc3kxMWFuZHB4K0p0LzV5YWxmaG1jbnh0VXZoczBQUW1ZMD0=" src="/core/vendor/underscore/underscore.js?v=738b385f38fa5473bc1770addb3de088"></script>
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<script nonce="Nit5T0NzaGpXNVg4N2NhbHcydXgzYWdITUdHVjQ2eWp4d3FMLzNDcDFmVT06M0tQRlBaSUFGc3kxMWFuZHB4K0p0LzV5YWxmaG1jbnh0VXZoczBQUW1ZMD0=" src="/core/vendor/moment/min/moment-with-locales.js?v=738b385f38fa5473bc1770addb3de088"></script>
02-04 11:29:56.235 E/OCSMSOwnCloudClient(9720): 					<script nonce="Nit5T0NzaGpXNVg4N2NhbHcydXgzYWdITUdHVjQ2eWp4d3FMLzNDcDFmVT06M0tQRlBaSUFGc3kxMWFuZHB`

**Comment by nerzhul** [comment]
can you provide your data/owncloud.log file please ? it's an error 500 server side

**Comment by enoch85** [comment]
@devz3r0 --^ Please :)

**Comment by devz3r0** [comment]
Hi, I was at lunch, here is the anonymized log:

`{"reqId":"OFRyEsUvh5EHN7Tn9Zzb","remoteAddr":"<MY-IP>","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'INSERT INTO oc_ocsms_smsdatas (user_id, added, lastmodified, sms_flags, sms_date, sms_id,sms_address, sms_msg, sms_mailbox, sms_type) VALUES (?,?,?,?,?,?,?,?,?,?)' with params [\\\"devzero\\\", \\\"2017-02-04 13:20:02\\\", \\\"2017-02-04 13:20:02\\\", \\\"11\\\", \\\"<ID>\\\", 89, \\\"+4<PHONE_NUMBER\\\", \\\"Ich trinke auf die Familie und gute Freunde , auf alte G\\\\u00f6tter, auf neue Ziele, auf den ganz normalen Wahnsinn und auf das was einmal war. Auf ein gutes neues Jahr. Prost \\\\ud83c\\\\udf78\\\\ud83c\\\\udf78\\\\ud83c\\\\udf89\\\\ud83d\\\\ude04  <NAME_OF_USER> \\\", 0, 1]:\\n\\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\\\xF0\\\\x9F\\\\x8D\\\\xB8\\\\xF0\\\\x9F...' for column 'sms_msg' at row 1\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO oc_...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/db\\\/statementwrapper.php(74): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/ocsms\\\/db\\\/smsmapper.php(289): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/ocsms\\\/controller\\\/apicontroller.php(82): OCA\\\\OcSms\\\\Db\\\\SmsMapper->writeToDB('devzero', Array)\\n#5 [internal function]: OCA\\\\OcSms\\\\Controller\\\\ApiController->push(104, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\OcSms\\\\Controller\\\\ApiController), 'push')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\OcSms\\\\Controller\\\\ApiController), 'push')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ApiController', 'push', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/ocsms\\\/pus...')\\n#13 \\\/var\\\/www\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","level":3,"time":"2017-02-04T13:20:02+00:00","method":"POST","url":"\/index.php\/apps\/ocsms\/push?format=json","user":"devzero","version":"11.0.1.2"}`

**Comment by nerzhul** [comment]
Encoding problem in database, do you use MySQL ?

**Comment by devz3r0** [comment]
Yes, generally that is not an issue with special german characters. i am using utf8_bin and innoDB

**Comment by devz3r0** [comment]
i did:
`ALTER TABLE oc_ocsms_smsdatas CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;`
that worked, but it didn't help.

**Comment by nerzhul** [comment]
@devz3r0 if i remember there is other things to do, maybe we should add this in README.md

**Comment by devz3r0** [comment]
that file would barely one see, who installs your app via the cloud-repo.

**Comment by enoch85** [comment]
I suddenly started to work for me, but I still get Error #9 quite often.

**Comment by devz3r0** [comment]
i applied the fixes on my mysql installation, 
https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html
now it's working, thanks.
