### ISSUE TITLE
Move strings

### ISSUE THREAD

**Issue by enoch85** [nerzhul/ownCloud-SMS-App#143]
This is an issue for you @AndyScherzinger ;)

https://github.com/nerzhul/ownCloud-SMS-App/issues/139#issuecomment-279258149

**Comment by enoch85** [comment]
Can't assign you, maybe @nerzhul can.

**Comment by nerzhul** [comment]
I don't want those strings to be moved, but yes we can mark them as not translatable

**Comment by nerzhul** [comment]
I'm tagging those values as not translatable now
