### ISSUE TITLE
Error #15 can't synchronize

### ISSUE THREAD

**Issue by harpogit** [nerzhul/ownCloud-SMS-App#147]
### Steps to reproduce
1. 
2.
3.

### Expected behaviour
Tell us what should happen
Trying to synchronize an android phone for the first time with Nextcloud on a local server (Yunohost 2.5.6 - Debian 8.7 32bit (Linux 3.16.0-4-armmp) 

### Actual behaviour
Tell us what happens instead
Error#15
### Server configuration

**Nextcloud version:** Nextcloud 11.0.2

**PHP version:**5.6.30

**Webserver:**

**HTTPS:**

### Client configuration

**Android version:** 4.1.2

**Phone:**Samsung GT-S6310N

**Nextcloud SMS app version:**0.24.1

### Logs

```
Insert your log here
```

**Comment by nerzhul** [comment]
Can you provide nextcloud server logs and if possible android logcat logs ?

Generally it means you didn't install the server side part

**Comment by harpogit** [comment]
Hi Nerzhul,

I'm afraid I don't know which log I've to provide. In /var/log/ there are plenty of log files, but no Nextcloud one.
$ ls /var/log/ give me :
```
alternatives.log       fail2ban.log.4.gz  openvpn-client.log
alternatives.log.1     faillog            openvpn-client.status
alternatives.log.2.gz  fontconfig.log     php5-fpm.log
alternatives.log.3.gz  fsck               php5-fpm.log.1
alternatives.log.4.gz  hypercube          php5-fpm.log.10.gz
alternatives.log.5.gz  kern.log           php5-fpm.log.11.gz
apt                    kern.log.1         php5-fpm.log.12.gz
auth.log               kern.log.2.gz      php5-fpm.log.2.gz
auth.log.1             kern.log.3.gz      php5-fpm.log.3.gz
auth.log.2.gz          kern.log.4.gz      php5-fpm.log.4.gz
auth.log.3.gz          lastlog            php5-fpm.log.5.gz
auth.log.4.gz          mail.err           php5-fpm.log.6.gz
bootstrap.log          mail.err.1         php5-fpm.log.7.gz
btmp                   mail.info          php5-fpm.log.8.gz
btmp.1                 mail.info.1        php5-fpm.log.9.gz
daemon.log             mail.info.2.gz     radicale
daemon.log.1           mail.info.3.gz     redis
daemon.log.2.gz        mail.info.4.gz     rspamd
daemon.log.3.gz        mail.log           samba
daemon.log.4.gz        mail.log.1         stunnel4
debug                  mail.log.2.gz      syslog
debug.1                mail.log.3.gz      syslog.1
debug.2.gz             mail.log.4.gz      syslog.2.gz
debug.3.gz             mail.warn          syslog.3.gz
debug.4.gz             mail.warn.1        syslog.4.gz
dmesg                  mail.warn.2.gz     syslog.5.gz
dpkg.log               mail.warn.3.gz     syslog.6.gz
dpkg.log.1             mail.warn.4.gz     syslog.7.gz
dpkg.log.2.gz          messages           unattended-upgrades
dpkg.log.3.gz          messages.1         user.log
dpkg.log.4.gz          messages.2.gz      user.log.1
dpkg.log.5.gz          messages.3.gz      user.log.2.gz
dpkg.log.6.gz          messages.4.gz      user.log.3.gz
dpkg.log.7.gz          metronome          user.log.4.gz
dpkg.log.8.gz          mysql              uwsgi
fail2ban.log           mysql.err          wtmp
fail2ban.log.1         mysql.log          wtmp.1
fail2ban.log.2.gz      nginx              yunohost
fail2ban.log.3.gz      ntpstats           yunohost-installation.log
```
I don't know either where to find Android logcat logs.
:(
I don't know what is the server side part.
:((
I just installed Nextcloud instance with sms synchro  **Phone Sync 1.11.5** on Yunohost server and **Nextcloud SMS** 0.24.1 and **Nextcloud beta** 201 70315 (synchro client) from FDroid.

Thank you for your kind help!

**Comment by nerzhul** [comment]
for logs, it should be in php5-fpm logs, please check the php errors related to our app here

**Comment by harpogit** [comment]
I've got only that in /var/log/php5-fpm.log :
``
[27-Mar-2017 06:25:09] NOTICE: error log file re-opened
``
??

**Comment by nerzhul** [comment]
Sorry but this error is only a log rotation.

Are you sure you installed ocsms app server side ?

**Comment by harpogit** [comment]
Do you talk about nextcloud/index.php/apps/ocsms/ ?
I got in on LaBrique (YunoHost), but I have only the message "Please choose a conversation on the left menu"
I'm lost.

**Comment by nerzhul** [comment]
okay, you don't have any message on the left column, nothing is synced

**Comment by harpogit** [comment]
Where should it come from then?
How could I test why it does not synchronize?
Thank you!

**Comment by nerzhul** [comment]
if app doesn't show messages, you will not see on nextcloud part.

You should provide logcat logs for your app, installing android SDK on your PR or if your phone is rooted you have apps to read them

**Comment by harpogit** [comment]
I don't have android sdk on my computer. It seems to require space that I don't have. I either don't know how to root my phone with a linux pc.
:-(

**Comment by nerzhul** [comment]
hmmm it will not be easy to debug then :(

**Comment by nerzhul** [comment]
seems fixed now, as we talked in another issue
