### ISSUE TITLE
#16 when AFWall allows connection only on Wifi

### ISSUE THREAD

**Issue by okias** [nerzhul/ownCloud-SMS-App#148]
I permanently getting error #16, when application is set to synchronize only over WiFi and AFWall is configured to allow only WiFi connections.

LineageOS 14.1 (Android 7.1.1)

**Comment by nerzhul** [comment]
what is afwall ?

**Comment by okias** [comment]
@nerzhul it's firewall, https://f-droid.org/repository/browse/?fdid=dev.ukanth.ufirewall&fdpage=2

**Comment by nerzhul** [comment]
are you able to recompile application to help us to find what is the problem ?

**Comment by okias** [comment]
I have Android studio installed, is it enough?

**Comment by nerzhul** [comment]
yeah, clone, and build it with it + launch it on your phone and look at the logs

**Comment by nerzhul** [comment]
i need to know what is the connection state reported by your firewall

**Comment by okias** [comment]
Well, running debug git version, no errors :(

**Comment by okias** [comment]
by longer examination of code: it seems to me, there is no way, to not have connection. When isValid() reports false for few times, it throw up error. But isValid behaviour is fine - I denied all mobile data and kept sync over wifi, so until I connect to WiFi, it's completly fine.

I propose change OCSyncException into Log.e or Log.i .

**Comment by nerzhul** [comment]
okay

**Comment by okias** [comment]
hold a second, issue is still valid. Problem is, it prints message, it should be quiet in these cases.
