### ISSUE TITLE
Don't show sync notification

### ISSUE THREAD

**Issue by schiessle** [nerzhul/ownCloud-SMS-App#150]
I'm using version 1.0.1 from f-droid. First let me say that the app works really great! I have just one small feature request:

It would be great if the user could disable the sync notification. The Notification is great for debugging or maybe for a first run to see that something happens. But in daily use it is really disturbing that this icons appears regularly in the notification area.

**Comment by nerzhul** [comment]
we can do that, noted :)

**Comment by okias** [comment]
Yes, please :)
