### ISSUE TITLE
[Wishlist] Request the compatibility with Owncloud 10

### ISSUE THREAD

**Issue by Rpnpif** [nerzhul/ownCloud-SMS-App#156]
After installing in /apps, Owncloud says that the 9.2 release or lower of owcloud is required and that, dependences are missing.

Please migrate ocsms to owncloud 10 with a valid signature of the code for this release of owncloud.

Regards.

**Comment by nerzhul** [comment]
hello, you are on the wrong repository, please go to https://github.com/nextcloud/ocsms and open the issue there
