### ISSUE TITLE
“Error #16: No data connection available” notification when data connection of the wrong type available

### ISSUE THREAD

**Issue by shtrom** [nerzhul/ownCloud-SMS-App#161]
When a data connection that has not been chosen in the General settings is present, a notification stating “Error #16: No data connection available” keeps being posted. This is noisy and incorrect, as a data connection is available, but not of a desired type, which is therefore ignored. The notification is not posted when no data connection (at all) is available.

It would make more sense to simply do nothing, and not post the notification

### Steps to reproduce
1. Select “Synchronise in Wi-Fi” only in the General settings
2. Turn on 3/4g, move outside of Wi-Fi range (alternatively, disable Wi-Fi)
3. Wait for the next sync (alternatively force it with “Synchronise now”, which will show a toast with the same message; it might be argued that manually using “Synchronise now” should actually ignore the network requirement)

### Expected behaviour
* Nothing gets synced until Wi-Fi is available
* No notification is shown

### Actual behaviour
* Nothing gets synced until Wi-Fi is available (/)
* A notification is virtually persistently shown (x)

**Comment by nerzhul** [comment]
This error is not present anymore
