### ISSUE TITLE
Since version 1.3.0 from FDROID the app cannot connect to the server.

### ISSUE THREAD

**Issue by gradinaruvasile** [nerzhul/ownCloud-SMS-App#162]
Since version 1.3.0 from FDROID the app cannot connect to the server.
Tried removing, reinstalling the app. Version 1.2.5 works fine.

When i insert the connection data, the client gives an error about not being able to perform a HTTP connection and on the server i have these in the logs:

Exception: The requested uri(/nextcloud/index.php/apps/ocsms/get/apiversion) cannot be processed by the script '/nextcloud//index.php')
    /var/www/nextcloud/lib/base.php - line 956: OC\AppFramework\Http\Request->getRawPathInfo()
    /var/www/nextcloud/index.php - line 48: OC handleRequest()
    {main}

My connection URL is https://my.domain:444/nextcloud. The same connection URI and user/password works on version 1.2.5.

### Steps to reproduce
1. Install Nextcloud SMS app 1.3.0 from FDROID
2. Insert connection details
3. Try to authenticate

### Expected behaviour
The app should connect to the server

### Actual behaviour
Client gives an error about not being able to perform a HTTP request.

### Server configuration

**Nextcloud version:** 
12.0.3
**PHP version:**
7.0
**Webserver:**
Apache 2.4.25
**HTTPS:**
Yes?
### Client configuration

**Android version:**
5.0.2
**Phone:**
Alcatel Idol 3 4.7"
**Nextcloud SMS app version:**
1.3.0
### Logs

```
Exception: The requested uri(/nextcloud/index.php/apps/ocsms/get/apiversion) cannot be processed by the script '/nextcloud//index.php')

    /var/www/nextcloud/lib/base.php - line 956: OC\AppFramework\Http\Request->getRawPathInfo()
    /var/www/nextcloud/index.php - line 48: OC handleRequest()
    {main}
```

**Comment by nerzhul** [comment]
Thanks for your report, i'm looking for this asap i noticed same problem on the autosync not in manual sync, can you confirm manual sync doesn't have problem on your phones ?

**Comment by ejstacey** [comment]
Manual sync (I reinit sync cursor so it has something to try and sync) does not do it for me.  It does seem to be only the auto sync.

**Comment by nerzhul** [comment]
okay i'm looking for this. 1.3 implemented refactor on the http client to use android native one but it seems something has been missed in auto sync

**Comment by nerzhul** [comment]
Okay here is the app logs

```
:29.078 488-948/fr.unix_experience.owncloud_sms I/fr.unix_experience.owncloud_sms.engine.OCHttpClient: Perform GET https://cloud.example.org/index.php/apps/ocsms/push?format=json
11-08 23:16:29.080 488-948/fr.unix_experience.owncloud_sms I/System: core_booster, getBoosterConfig = false
11-08 23:16:29.087 488-948/fr.unix_experience.owncloud_sms I/System: core_booster, getBoosterConfig = false
11-08 23:16:29.625 488-948/fr.unix_experience.owncloud_sms I/OCSMSOwnCloudClient: SMS Push request said: status false - Error: smsCount field is NULL
```

**Comment by nerzhul** [comment]
Strangely in this request POST data is empty

**Comment by nerzhul** [comment]
Fixed
