### ISSUE TITLE
Unable to add account throught IP without domain name

### ISSUE THREAD

**Issue by Myppomeu** [nerzhul/ownCloud-SMS-App#164]
### Steps to reproduce
1. Install 1.3.x branch
2. Try to add acount throught IP without domain name

### Expected behaviour
Added account.

### Actual behaviour
Nextcloud SMS returns an error telling that it cannot establish HTTP connection.
There is no such error in Nextcloud SMS 1.2.5

### Server configuration

**Nextcloud version:** 12.0.3

**PHP version:** 5.6.30+dfsg-0+deb8u1

**Webserver:** nginx 1.6.2-5+deb8u5

**HTTPS:** no

### Client configuration

**Android version:** 7.1.2 (LineageOS 14.1)

**Phone:** Xiaomi Redmi Note 3 Pro (replicates on every phone I test)

**Nextcloud SMS app version:** 1.3.0 and 1.3.1

**Comment by nerzhul** [comment]
Hello
it's fixed in 1.3.2 branch, the /api/version call is broken is 1.3.0 and 1.3.1.

Thanks for your report
