### ISSUE TITLE
Nextcloud SMS 1.3.0+ breaks login / sync sms to nextcloud

### ISSUE THREAD

**Issue by adi2k5** [nerzhul/ownCloud-SMS-App#168]
### Steps to reproduce
1. Upgrade nextcloud SMs to 1.3.0 / 1.3.1
2. Try to sync sms, or
3. Try to create new account for nextcloud SMS (if there was none or it's been removed)

### Expected behaviour
Sync SMS / create an account and sync

### Actual behaviour
When trying to sync sms when account was present in app before upgrade to 1.3.0, app throws error '# 13 authorization error' or something similiar - sorry that I can't provide exact error, but I've downgraded app to 1.2.5 already. 
Once you'll remove account (or if it wasn't present prior to installing app in v 1.3.0+) and try to create new one, app will throw error "Can't initialize http connection. Please check that web server is running". 
Very similar issue was raised on https://help.nextcloud.com/t/phonesync-app-ocsms-no-sync-then-no-connection-http-405/23301, but creator doesn't (and doesn't want to) have github account to open issue. 
The only difference is, that I don't have problem with "Invalid argument supplied for foreach()".

On server side everything is running and working as expected, all other apps from phone are working perfectly fine. 

### Server configuration

**Nextcloud version:** 
12.0.3.3
**PHP version:** 
7.1
**Webserver:**
lighttpd
**HTTPS:**
yes
### Client configuration

**Android version:**
6
**Phone:**
n/a
**Nextcloud SMS app version:**
1.3.0 and 1.3.1
### Logs
From nextcloud.log:
```
{"reqId":"1T4E2pnBJktiDwsBirFe","level":1,"time":"2017-11-21T10:36:34+00:00","remoteAddr":"$myip","user":"--","app":"admin_audit","method":"POST","url":"\/index.php\/apps\/ocsms\/get\/apiversion?format=json","message":"Login attempt: \"$myuser\"","userAgent":"nextcloud-phonesync (1.3.1)","version":"12.0.3.3"}

```
From web server log:
```
$myip $myaddress - [21/Nov/2017:10:37:41 +0100] "POST /index.php/apps/ocsms/get/apiversion?format=json HTTP/1.1" 405 20 "-" "nextcloud-phonesync (1.3.1)"

```
One thing I've noted here is, that 1.3.0 and above are using POST method (which seem to be causing 405 - method not allowed), while for 1.2.5 I can see in logs mostly only GET method - and in this case all is working as expected.

**Comment by nerzhul** [comment]
Use 1.3.2 version
