### ISSUE TITLE
Can't restore messages from server to a new phone.

### ISSUE THREAD

**Issue by CapSel** [nerzhul/ownCloud-SMS-App#183]
### Steps to reproduce
1. add account in App
2. select restore all messages

### Expected behaviour
All messages should be downloaded from server.

### Actual behaviour
Just fast message in green about success.

### Server configuration

**Nextcloud version: 13.0.0** 

**PHP version: 7.0**

**Webserver: apache-2.4.6**

**HTTPS:certbot**

### Client configuration

**Android version: 7.1.2**

**Phone:Asus Zenfone 2**

**Nextcloud SMS app version: 1.12.2**

### Logs

```
02-24 11:49:48.552  5501  7781 E OCSMSOwnCloudClient: Invalid response received from server, either messages or last_id field is missing.
02-24 11:49:48.552  5501  7781 I ASyncSMSRecovery: Retrieved returns failure
```

**Comment by nerzhul** [comment]
Can you look at your apache/nginx access logs and show me the call logs for the restore period please ?

**Comment by CapSel** [comment]
```
89.72.255.191 - - [27/Feb/2018:22:38:59 +0100] "GET /nextcloud/index.php/apps/ocsms/api/v2/messages/0/500?format=json HTTP/1.1" 200 73841
```
This the only line in apache logs - nothing more in error_log or access_log.

There are no logs in admin panel of nextcloud related to ocms.

**Comment by nerzhul** [comment]
The call sounds to be good in terms of call, return code and size. Can you look at the response body in a tcpdump or anything else ?

**Comment by CapSel** [comment]
I'll try to temporarily disable SSL this evening (eta 7h).

**Comment by CapSel** [comment]
There is a valid json like this:
```
{"messages":
  {"123456":
    {"address":"some string",
     "mailbox":"0",
     "msg":"some content",
     "type":"2"
    },
    ... other messages
   "last_id":"1234"
}
```

Some chars looks like this: "pu\u015b\u0107"

Request and headers:
```
GET /nextcloud/index.php/apps/ocsms/api/v2/messages/0/500?format=json HTTP/1.1
Host: v-matrix.org
User-Agent: nextcloud-phonesync-go (2.0.3)
Accept: application/json
Authorization: Basic Y2Fwc2VsOktvY2hhbU1vamVNeXNpdQ==
Content-Type: application/json
Accept-Encoding: gzip

HTTP/1.1 200 OK
Date: Thu, 01 Mar 2018 23:09:32 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
X-Powered-By: PHP/7.0.10
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
X-Frame-Options: SAMEORIGIN
Cache-Control: no-cache, no-store, must-revalidate
Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self' ;media-src 'self' blob:;child-src 'self'
Set-Cookie: oc_sessionPassphrase=UNYWAyntmSpAs4gBhgIKJJGKPzOItlySQbbuuUAjRRm0RTRBJOzQCnDLuMabyBLGThyAOtY0zqNIb%2FjrYzTujNZBp3g5MTKShBSFvF3eLm0GapRRb2fHlD95k6%2Bod53Q; path=/nextcloud; HttpOnly
Set-Cookie: nc_sameSiteCookielax=true; path=/nextcloud; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
Set-Cookie: nc_sameSiteCookiestrict=true; path=/nextcloud; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
Set-Cookie: ock178l212tc=krjnrbiksemo8sda501p7g4gc1; path=/nextcloud; HttpOnly
Set-Cookie: cookie_test=test; expires=Fri, 02-Mar-2018 00:09:32 GMT; Max-Age=3600
Strict-Transport-Security: max-age=15552000; includeSubDomains
Content-Length: 73809
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Content-Type: application/json; charset=utf-8

[valid json body]
```
types are only "1" and "2"
mailboxes are "0" and "1"
not all addresses are numbers - some are names
some msgs are multiline
There are exactly 500 messages there.

I don't want to paste sms content here.

**Comment by CapSel** [comment]
Oh and ids (like "123456") are not ordered/sorted.

**Comment by nerzhul** [comment]
Thanks for the dump. Ordering is not important. For the chars you mentioned it's UTF-8 encoded.

**Comment by w0k3** [comment]
Same issue here, anything I can do to help resolving it?

**Comment by nerzhul** [comment]
@w0k3 i need to verify the restore algorithm to ensure messages are correctly ingested by the client. I notice the app version is quite old. Can you use 2.0.3 ?

**Comment by w0k3** [comment]
I am using version 2.0.3 on Android 8.0.0. I can see hundreds of messages in nextcloud web interface /apps/ocsms, but in my new phones there are 0 of them. If I try to restore all SMS, I set the permissions and default SMS app, a spinner shows up for about a second, then a successful message shows for a fraction of second and then I see the button again. No messages are restored.

**Comment by nerzhul** [comment]
Okay i can reproduce it, i'm trying to find the issue

**Comment by nerzhul** [comment]
Partially fixed by https://gitlab.com/nerzhul/ncsmsgo/commit/c518f33c218604620ce02e2eb26beb8100adcc27

**Comment by nerzhul** [comment]
Another fix
https://gitlab.com/nerzhul/ncsmsgo/commit/4e143a9262e0eef446f5d54d7615647e97204e0c

Basically it's date issue, 32b vs 64b, i'm fixing the issues currently

**Comment by nerzhul** [comment]
This repo commits:

7af398786efacbbd5f2345017bcaff427ac98324
15c9617a2b00a01fe5570f6e4cb46c99a1cee9c3

**Comment by nerzhul** [comment]
It's now fixed. 2.0.4 will be release asap

**Comment by w0k3** [comment]
Thank you @nerzhul, will test it asap.

**Comment by w0k3** [comment]
I've made a debug build of 2.0.4 and installed to phone, sadly, I am still unable to download old messages to my new phone. Are there any log files I can check?

**Comment by w0k3** [comment]
Yes of course, thanks.
