### ISSUE TITLE
App does not sync new SMS, synchronization cursor has to be reinitialized every time 

### ISSUE THREAD

**Issue by e-alfred** [nerzhul/ownCloud-SMS-App#185]
### Steps to reproduce
1. Set up Nextcloud SMS app with an account
2. Recieve SMS

### Expected behaviour
SMS should be synced to Nextcloud and show up in the Nextcloud SMS app.

### Actual behaviour
SMS aren't synced (saying "Nothing to sync"), synchronization cursor has to be reinitialized, then a sync works. See issue https://github.com/nextcloud/ocsms/issues/215. Tested with two different phones (BQ X5 Plus/Samsung Galaxy S3).

### Server configuration

**Nextcloud version:** 12.0.5

**PHP version:** 7.0

**Webserver:** Apache 2.4

**HTTPS:** Yes, with official cert from a trusted CA

### Client configuration

**Android version:** 7.1.1/7.1.2

**Phone:** BQ X5 Plus/Samsung Galaxy S3

**Nextcloud SMS app version:** 2.0.2

### Logs

```
{"reqId":"WprpKH8AAQEAAD0iMv0AAAAA","level":1,"time":"2018-03-03T19:27:52+01:00","remoteAddr":"1.1.1.1","user":"--","app":"admin_audit","method":"GET","url":"\/cloud\/index.php\/apps\/ocsms\/get\/smsidlist?format=json","message":"Login attempt: \"user\"","userAgent":"nextcloud-phonesync-go (2.0.2)","version":"12.0.5.3"}
```

**Comment by deaddivest** [comment]
same here.. anyone?

**Comment by 9662** [comment]
For me, even reinitialising the cursor does not work. Nothing has been synced since February.

Running 2.0.4 on two phones, 1.12.2 on NC13.0.1

**Comment by nerzhul** [comment]
Sorry, i got some problems IRL and i didn't get time to fix that issue, will look at this problem asap

**Comment by nn10nn10** [comment]
Also having this issue. I thought I was doing something wrong and kept rechecking all settings and my nextcloud setup.

Looking forward to that fix :)

**Comment by deaddivest** [comment]
Please clarify (someone), is this problem affect everyone or just a few users?

**Comment by nn10nn10** [comment]
Reading over the comments I believe it is an issue everyone is having. @nerzhul said that he hasn't had time to fix the issue yet so I think he knows what's going on.

**Comment by 9662** [comment]
For info, as of 1.12.7 sync is working again. Thanks! :+1:

**Comment by nerzhul** [comment]
please update to last release

**Comment by e-alfred** [comment]
Works now, thanks!
