### ISSUE TITLE
Enhancement: Ignoring specific conversations of texts?

### ISSUE THREAD

**Issue by cengbrecht** [nerzhul/ownCloud-SMS-App#20]
I would like to propose that we ignore conversations (Texts) that are from senders with less than 6 numbers for a number. 
As most routing of phones requires a minimum of 7 numbers for a phone number to be valid. 

(I get texts from my voicemail telling me I have voicemail, and its just stupid.)

**Comment by nerzhul** [comment]
I think we could work on this issue for next release :)

**Comment by nerzhul** [comment]
This feature was implemented in previous release
