### ISSUE TITLE
Fdroid?

### ISSUE THREAD

**Issue by jas4711** [nerzhul/ownCloud-SMS-App#21]
Have you considered pushing this app into fdroid?  Any reason doing so would be a bad idea?  I can look into it if you don't have anything against that.

**Comment by dvarum12** [comment]
and mine :)
it is for open source apps

**Comment by RealRancor** [comment]
Created an Merge Request to include the app into f-droid: https://gitlab.com/fdroid/fdroiddata/merge_requests/521

**Comment by nerzhul** [comment]
Hmmm, it's not very fair play to do this @RealRancor , whereas i'm application maintainer. But thanks.

You forget one lib, ownCloud-Client library is missing, and i modified it for Google Play Store before packaging apk because of HTTPS handling, then the commit you send will not work in some configurations.

**Comment by RealRancor** [comment]
@nerzhul 
Which ownCloud-Client library are you referring? The two libraries included in your current project:

https://github.com/nerzhul/ownCloud-SMS-App/blob/master/project.properties#L15-L16

are build on f-droid.

Btw. if you don't want so have your app distributed you need to choose a license which disallows this.

**Comment by nerzhul** [comment]
It's not a licence problem :) I need to manage the distribution channel, because of updates, the Android App cannot follow each github commit

**Comment by RealRancor** [comment]
You don't need to worry about updates on f-droid as there is an automated update check there.

If you're using tags for your releases the updates could be also build automatically.

**Comment by nerzhul** [comment]
okay, i think we must use tag is you need F-Droid update, because master branch is devel branch, and users mustn't have broken app.

**Comment by RealRancor** [comment]
I have chosen this commit for the release https://github.com/nerzhul/ownCloud-SMS-App/commit/6480b3dbbdc1474502697f1d53a51627ad052c5b which was the correct one for 1.6.1 according to your commit log.

On f-droid we try to don't use the latest commit for an release but choosing the correct commit for the release of the app according to the commit logs. Proper tagging of the releases is always helpful so we don't need to check the commit logs.

**Comment by nerzhul** [comment]
Of course . When 2.0 will be released tagging will be available on github

**Comment by nerzhul** [comment]
FDroid unofficial support has been added by @RealRancor 

@RealRancor do you want to became maintainer of the F-Droid app ?

**Comment by RealRancor** [comment]
@nerzhul 
If releases are properly tagged no maintainer is needed. But i can have a look at the app when problems arise.

**Comment by jas4711** [comment]
Thanks for packaging it, I'm now using the app via fdroid and it appears to work -- at least my SMSs were pushed to my OC instance.  Time to close this?

**Comment by nerzhul** [comment]
@RealRancor there is a tag now. 0.17.0 where tagged

**Comment by RealRancor** [comment]
@nerzhul
Thanks for the notification. 0.17.0 was already build on f-droid:

https://f-droid.org/repository/browse/?fdfilter=Owncloud&fdid=fr.unix_experience.owncloud_sms

:1:

**Comment by computerfr33k** [comment]
Seems the latest version no longer compiles on F-Droid, I have tried updating the build, but it complains about not finding the AndroidManifest. It's not just me because the latest version is also not available on the F-Droid repo as well.

```bash
Error: . is not a valid project (AndroidManifest.xml not found).
ERROR: Could not build app fr.unix_experience.owncloud_sms: Failed to update project at .
==== detail begin ====
Error: . is not a valid project (AndroidManifest.xml not found).
`

**Comment by nerzhul** [comment]
@computerfr33k warning we switched from eclipse to Android Studio
