### ISSUE TITLE
Install doesn't create a shortcut, running from play store doesn't work

### ISSUE THREAD

**Issue by frankerooney** [nerzhul/ownCloud-SMS-App#22]
Hi. Just bought and installed the app from play store (LG G3 with lollipop) and it didn't install a shortcut, and doesn't work when I open it from the play store using the ... button from the search dialog (no other way available of opening it).
Strangely if I go into the list of apps in the play store there is an "open" button for all apps but this one, just uninstall available, the open option only appears by searching for the app and click only the vertical row of dots. Hope that makes sense.
Any ideas?
Thanks
Andy

**Comment by nerzhul** [comment]
Hi @frankerooney ,
There are no shortcut. OwnCloud SMS is a connector. Please go to Parameters => Account => Add Account.

**Comment by frankerooney** [comment]
Ho hum, I look a bit thick then. I did have a quick look in accounts & sync but didn't add anything so the sms thing didn't show up. Thanks for your help!
andy

**Comment by nerzhul** [comment]
HI @frankerooney sorry for to be late. I'm looking at your issue but i have problem with Eclipse today. I'll add a shortcut to help new users to use owncloud SMS app.

**Comment by nerzhul** [comment]
HI @frankerooney , https://github.com/nerzhul/ownCloud-SMS-App/commit/b8f8d3d23f25e91ac0aa6aa2ee7bd5a049a4f7d3 prepare a main activity for ownCloud SMS app.

I let your issue opened, what do you think we can set into it ?

**Comment by nerzhul** [comment]
Fixed. It will be ready in 0.17
