### ISSUE TITLE
Spanish translation of Play Store Description

### ISSUE THREAD

**Issue by agdg** [nerzhul/ownCloud-SMS-App#27]
La aplicación ownCloud SMS sincroniza sus mensajes SMS en un servidor ownCloud remoto y le permite leer sus mensajes desde él.

El envio de SMS desde el servidor ownCloud será implementado en futuras versiones.

La aplicación es totalmente compatible con Android 4.0 a 5.0

**Comment by agdg** [comment]
I sorry, i did not see that values-es/google_playstore_strings.xml exist. 

I created a pull request on values-es/google_playstore_strings.xml for auto-merged.

**Comment by nerzhul** [comment]
Thanks for your contribution :)
