### ISSUE TITLE
[bug]  Conversations splitted in two because of Intl number format

### ISSUE THREAD

**Issue by theonlydoo** [nerzhul/ownCloud-SMS-App#3]
from https://github.com/nerzhul/ocsms/issues/6#issuecomment-60221396, It might be a good idea to re-implement the international/local number mapping inside the app, ideed.

**Comment by nerzhul** [comment]
@theonlydoo it's now fixed, i forget to close this issue. Please update your ocsms app on owncloud and set a language in app settings.

**Comment by theonlydoo** [comment]
I'll try soon, thx for the feedback :-)

**Comment by ericfont** [comment]
I see conversations for a number 1########## are split when used with the identical number but with a "+" in front: +1##########.  I notice this issue now in the current version ownCloud SMS v1.4.3 (which was automatically updated when I updated owncloud server, I believe as I don't remember manually updating).  I don't know if this is the same issue and has been fixed or if this is different, or if I need to do something like update some database.

**Comment by nerzhul** [comment]
I also notice the bug. I will review the modification on deduplication model.

**Comment by nerzhul** [comment]
This is definitively a ocsms for server problem.
