### ISSUE TITLE
Error #9: Server set unhandled HTTP return code

### ISSUE THREAD

**Issue by eyesoftsys** [nerzhul/ownCloud-SMS-App#34]
i'am getting on client this error, on logs i see "Server set unhandled HTTP return code 500" is a problem with owncloud server, can you make status code 500 handled and set a better error description. From a  owncloud sms client perspective it's not an error, from a owncloud sms server this is an error.

Server

ownCloud version: 7.0.4 (stable)
PHP version: PHP 5.6.5 
HTTPd server: Apache/2.4.10
HTTPS: Apache/2.4.10
mysqld :  5.6.17

Client

Android version: 4.2.2
Phone: - 
ownCloud SMS app version: 0.17.0

Thank you

**Comment by eyesoftsys** [comment]
on server side the error was this : SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: 'NOW()' for column 'added' at row 1

solved in file apps/ocsms/db/smsmapper.php by adding :
+262 $today = date("Y-m-d H:i:s");
and change "NOW()","NOW()" with $today, $today

**Comment by nerzhul** [comment]
what is your database backend ?

**Comment by nerzhul** [comment]
can you send your issue on the proper github repo ?

**Comment by eyesoftsys** [comment]
done : https://github.com/nerzhul/ocsms/issues/55

**Comment by nerzhul** [comment]
Thanks, i close this issue

**Comment by eyesoftsys** [comment]
ok, but i think you need to handle error 500

**Comment by nerzhul** [comment]
not on android app this permit to detect bugs on server side
