### ISSUE TITLE
more info on "connection failed, ensure this is a right server"

### ISSUE THREAD

**Issue by cptMikky** [nerzhul/ownCloud-SMS-App#39]
I keep getting this error when creating an account. I'm positive all information entered is correct. Same information works with official ownCloud sync app. I'd appreciate more information in the error message. I suspect a certificate problem but cannot tell for sure. 

App version: 0.17.0 (F-Droid)
Android: 4.4.4 (CM11)
Phone: Xperia ZR

Also, if this turns out to be a certificate problem (be it self-signed, unknown CA or expired), there should be an override option since the connection still gets encrypted and trustworthiness of a certificate should ultimately be decided by the user - provided detailed info on the certificate is displayed to the user prior its acceptance.

**Comment by nerzhul** [comment]
Hi,
are you using it from F-Droid ? F-Droid doesn't include our patched library, and is not supported officially.

**Comment by cptMikky** [comment]
Hi, yes, F-Droid. Any chance it will be supported? And what kind of library are you referring to? Are you sure the problem is in fact related to the patched library?

**Comment by nerzhul** [comment]
i refer to owncloud library. Yes because i patched it to allow self certificates, the default doesn't permit it.

**Comment by cptMikky** [comment]
I see. Thanks for the information, I'll look deeper into what might be the problem with the certificate. However, as I mentioned before, the ownCloud app itself works with the very same server and certifiate and has worked since version 1.5.x I think. I can only guess that the app also uses the ownCloud library...

Anyway, if I can, I'd suggest working on error messages. It looks nice enough but it lacks the important information. Not just the one I see, I tried logging in with deliberately wrong password and got only the text "UNK", which is, say, inconclusive :)

**Comment by nerzhul** [comment]
You are right, but the API doesn't return a very simple exception to handle for the certificate. Maybe modify it in the future :)

**Comment by AW-UC** [comment]
@cptMikky had the same issue. Does your URL ends with `.../owncloud/`? If so, remove the trailing `/`. Also make sure, your URL doesn't iclude `https://`.

**Comment by cptMikky** [comment]
I should probably mention that even though this issue is still valid somehow, it shoud have a lower priority, apart from having a better error message. The certificate I was using wasn't exactly valid, it was expired, which on it's own doesn't affect the crypto part (as long as **I** trust the certificate, it's still OK to use it) but it kinda defeats the purpose of the "certification" thingie. Updating the certificate made things work again. I'll keep this issue open since in my opinion what I did is in fact more of a workaround than a solution. Unless @nerzhul thinks otherwise, of course :)

**Comment by nerzhul** [comment]
@AW-UC thanks for the report, will looking at this soon
@cptMikky no problem

**Comment by stalker145** [comment]
LG G3 running official Verizon Android 5.1.1 receives "Unk" error when attempting to connect to Raspberry Pi 2 running Raspbian and ownCloud 8.1.3 with a self-signed certificate via https. Is there any further on this error?

**Comment by i2bator** [comment]
Any updates on this bug? thanks

**Comment by nerzhul** [comment]
@i2bator sorry for to be late, i'm very busy IRL and the only developper on the project atm (except some contributions). If i get some time, i will look at this this weekend

**Comment by nerzhul** [comment]
@stalker145 @i2bator when next release will be published we will handle a little bit more properly return codes to give users a better message

**Comment by monsieurpouet** [comment]
I've a same issue :(
I put in the field, may server address and I've the error: "connection failed, ensure this is a right server".
I used to a self-signed certificate too.

**Comment by nerzhul** [comment]
@monsieurpouet do you use the official play store version ?
The information enhancement hasn't been released yet because i need to finish a new feature

**Comment by nerzhul** [comment]
This has been improved
