### ISSUE TITLE
Don't repeat synchronization after fail

### ISSUE THREAD

**Issue by pejakm** [nerzhul/ownCloud-SMS-App#53]
Main reason I set update interval to `Never` and therefore experienced #31 is because my ownCloud server is on my own computer, which isn't always on, and ownCloud-SMS keeps trying to connect to it indefinitely. So it makes sense to introduce a mechanism of silent fail: when the server can't be reached (or otherwise synchronization fails for some other reason) app will not trying to connect again until next scheduled sync.

**Comment by nerzhul** [comment]
The application is scheduled to do a triggered sync on
- Network change (to push the non push-on-received messages because of not available data connection)
- Periodic sync

If i add an option to disable the trigger on network change does that fit ?

**Comment by pejakm** [comment]
> The application is scheduled to do a triggered sync on network change (to push the non push-on-received messages because of not available data connection)

I wasn't aware of this. :) Since I don't have this "push-on-received" (even don't know what is that), yes and option to disable trigger on network change would be very much appreciated, thanks. :)

**Comment by nerzhul** [comment]
push-on-receive : push the received SMS when you receive it if data is available.
You don't have notification shown for this it's done transparently to ensure the data is transfered to server

**Comment by pejakm** [comment]
Push to where? :) Never mind, I still wont use this, so I would really love to see this option. :)

**Comment by nerzhul** [comment]
To you owncloud instance :)

**Comment by nerzhul** [comment]
@pejakm sorry for to be late. I add this option soon :)

**Comment by pejakm** [comment]
:+1:

**Comment by nerzhul** [comment]
It's now implemented in master. I close the issue.
