### ISSUE TITLE
Wrong VC/VN for 0.18.2 tag

### ISSUE THREAD

**Issue by RealRancor** [nerzhul/ownCloud-SMS-App#55]
Hi,

just tried to build the current version 0.18.2 on f-droid but failed because the 0.18.2 tag still contains the VC 24 and VN 0.18.1:

https://github.com/nerzhul/ownCloud-SMS-App/blob/0.18.2/AndroidManifest.xml#L4-L5

**Comment by nerzhul** [comment]
Thanks for the note, i fix it now, i forget it :)

**Comment by nerzhul** [comment]
This will be fixed on next release of the app

**Comment by nerzhul** [comment]
Tag 0.18.5 is now properly set
