### ISSUE TITLE
"Sync all messages" issue

### ISSUE THREAD

**Issue by Jef2i** [nerzhul/ownCloud-SMS-App#56]
I've got problems syncing my messages from my android messages.
Well. I've played a little with the tool before having synchronization partially working, then failed...

### Explanations
* OC Sv7
 - sync fails reported by Android app (timeout) (server-side's logs : getCrypto undefined method)
* OC Sv8 migration completed
 - (*after migration*) no sync (server-side's logs : SQL error)
```
{"reqId":"8a0463b8744XXXXXXXX8c0314a4383af","remoteAddr":"192.168.1.254","app":"index","message":"Exception: {
    "Message":"An exception occurred while executing 'SELECT sms_address,count(sms_date) as ct FROM oc_ocsms_smsdatas WHERE user_id = ? AND sms_mailbox IN (?,?) AND sms_date > ? GROUP BY sms_address' with params ['<USER>', 0, 1, '']:
        SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ''",
    "Code":0,"Trace":"
            #0 /volume1/web/owncloud_8.0.2/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))
            #1 /volume1/web/owncloud_8.0.2/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT sms_addr...', Array)
            #2 /volume1/web/owncloud_8.0.2/lib/private/db/statementwrapper.php(63): Doctrine\\DBAL\\Statement->execute(Array)
            #3 /volume1/web/owncloud_8.0.2/apps/ocsms/db/smsmapper.php(204): OC_DB_StatementWrapper->execute(Array)
            #4 /volume1/web/owncloud_8.0.2/apps/ocsms/controller/smscontroller.php(164): OCA\\OcSms\\Db\\SmsMapper->getNewMessagesCountForAllPhonesNumbers('bertrand', '')
            #5 [internal function]: OCA\\OcSms\\Controller\\SmsController->checkNewMessages('')
            #6 /volume1/web/owncloud_8.0.2/lib/private/appframework/http/dispatcher.php(158): call_user_func_array(Array, Array)
            #7 /volume1/web/owncloud_8.0.2/lib/private/appframework/http/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\OcSms\\Controller\\SmsController), 'checkNewMessage...')
            #8 /volume1/web/owncloud_8.0.2/lib/private/appframework/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\OcSms\\Controller\\SmsController), 'checkNewMessage...')
            #9 /volume1/web/owncloud_8.0.2/lib/private/appframework/routing/routeactionhandler.php(44): OC\\AppFramework\\App::main('SmsController', 'checkNewMessage...', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)
            #10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)
            #11 /volume1/web/owncloud_8.0.2/lib/private/route/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)
            #12 /volume1/web/owncloud_8.0.2/lib/base.php(767): OC\\Route\\Router->match('/apps/ocsms/get...')
            #13 /volume1/web/owncloud_8.0.2/index.php(36): OC::handleRequest()
            #14 {main}",
    "File":"/volume1/web/owncloud_8.0.2/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php","Line":91}",
"level":4,"time":"2015-04-12T20:21:13+00:00"}
```
 -  (*server-side deletion of oc_ocsms_ tables + oc_appconfig "ocsms" entries + app files + new app install*) sync of today's messages
 - (*account deletion on android app + account re creation*) nothing more, only today's messages remains having been synced previously
 - (*another deletion of everything server-side + account deletion terminal-side + reinstallation of everything + "auto-sync" disabled terminal-side*) nothing is synced. SMS panel into web interface is empty. "smsdatas" table too. **Same SQL message**

Something else I should try ?

**Comment by AW-UC** [comment]
Maybe some of the SMS on your phone don't have proper `sms_date` values? Or any other malformed SMS? I made your log output more readable:

    {"reqId":"8a0463b8744XXXXXXXX8c0314a4383af","remoteAddr":"192.168.1.254","app":"index","message":"Exception: {
		"Message":"An exception occurred while executing 'SELECT sms_address,count(sms_date) as ct FROM oc_ocsms_smsdatas WHERE user_id = ? AND sms_mailbox IN (?,?) AND sms_date > ? GROUP BY sms_address' with params ['<USER>', 0, 1, '']:
			SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ''",
		"Code":0,"Trace":"
				#0 /volume1/web/owncloud_8.0.2/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))
				#1 /volume1/web/owncloud_8.0.2/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT sms_addr...', Array)
				#2 /volume1/web/owncloud_8.0.2/lib/private/db/statementwrapper.php(63): Doctrine\\DBAL\\Statement->execute(Array)
				#3 /volume1/web/owncloud_8.0.2/apps/ocsms/db/smsmapper.php(204): OC_DB_StatementWrapper->execute(Array)
				#4 /volume1/web/owncloud_8.0.2/apps/ocsms/controller/smscontroller.php(164): OCA\\OcSms\\Db\\SmsMapper->getNewMessagesCountForAllPhonesNumbers('bertrand', '')
				#5 [internal function]: OCA\\OcSms\\Controller\\SmsController->checkNewMessages('')
				#6 /volume1/web/owncloud_8.0.2/lib/private/appframework/http/dispatcher.php(158): call_user_func_array(Array, Array)
				#7 /volume1/web/owncloud_8.0.2/lib/private/appframework/http/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\OcSms\\Controller\\SmsController), 'checkNewMessage...')
				#8 /volume1/web/owncloud_8.0.2/lib/private/appframework/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\OcSms\\Controller\\SmsController), 'checkNewMessage...')
				#9 /volume1/web/owncloud_8.0.2/lib/private/appframework/routing/routeactionhandler.php(44): OC\\AppFramework\\App::main('SmsController', 'checkNewMessage...', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)
				#10 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)
				#11 /volume1/web/owncloud_8.0.2/lib/private/route/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)
				#12 /volume1/web/owncloud_8.0.2/lib/base.php(767): OC\\Route\\Router->match('/apps/ocsms/get...')
				#13 /volume1/web/owncloud_8.0.2/index.php(36): OC::handleRequest()
				#14 {main}",
		"File":"/volume1/web/owncloud_8.0.2/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php","Line":91}",
	"level":4,"time":"2015-04-12T20:21:13+00:00"}

**Comment by Jef2i** [comment]
I don't really know if I have some malformed SMS. But I don't think :-)
I used to use "textra" to send/receive SMS, TitaniumBackup to backup/restore then.

But please note that when I had SMS syncing correctly working, I had **only** day's SMS synced. Nothing from the days before.

(@AW-UC: thank you for the log's display corrections. I've updated my initial post)

**Comment by nerzhul** [comment]
Hello @Jef2i , the algorithm sent every messages which is not on server based on its ID. This will change with next version which don't care about SMS_ID which is not unique after a restore, we will look at SMS_ID + SMS_DATE (which is unique).
For the invalid date i will add a test to check the problem, thanks for the trace

**Comment by nerzhul** [comment]
Fixed, thanks and sorry for to be late !

https://github.com/nerzhul/ocsms/commit/ab5792e39f6e1fb0739fc986701c2fb1a36068d6
