### ISSUE TITLE
Sync error Error #9 Server set unhandled h... 

### ISSUE THREAD

**Issue by pappabetalar** [nerzhul/ownCloud-SMS-App#59]
Hi I am running the latest Android app.
Phone: Huawei P7-L10
Androi: 4.4.2

Owncloud server hosted on Ubuntu server with ssl.
ownCloud 8.0.2 (stable).

Is there anyway i can extract logs from the app or server to see what's going wrong?
I get Error #9 Server set unhandled h... (I can't see the rest of the message)

This might be due to the large amount of sms i am trying to sync? about 10k+

I have tried syncing over Wifi/4G both end up with errors. I have seen a couple of different error codes, nut never wrote them down. Will do from now on.

**Comment by nerzhul** [comment]
Hi, you can find the problem on server generally for error #9. Look at your php_error.log, apache logs and owncloud/data/owncloud.log

**Comment by pappabetalar** [comment]
I will look through my server logs, guessing this is a server issue and not something with the app or owncloud sms itself.

Exception: {"Message":"An exception occurred while executing 'DELETE FROM oc_ocsms_smsdatas WHERE user_id = ? AND sms_id = ?' with params [\"XXXX\", 11216]:\n\nSQLSTATE[HY000]: General error: 1205 Lock wait 

You can close this if this is an issue with my server set up.
Thanks for the reply.

**Comment by nerzhul** [comment]
Are you using sqlite ?

**Comment by pappabetalar** [comment]
I ma using "mysql  Ver 14.14 Distrib 5.6.24, for debian-linux-gnu (x86_64) using  EditLine wrapper"

**Comment by nerzhul** [comment]
The lock wait problem is on your database, owncloud database connector waits for your database and generate a timeout.
The DELETE is working, but not applied because of your database reponsivity

**Comment by pappabetalar** [comment]
Thank you for this, i will investigate further.

**Comment by nerzhul** [comment]
Are you using a RPI or another little system ?

**Comment by pappabetalar** [comment]
It's an old laptop, not the best but it should be enough.
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 15
Model name:            Intel(R) Core(TM)2 Duo CPU     T7250  @ 2.00GHz
Stepping:              13
CPU MHz:               1200.000
CPU max MHz:           2001.0000
CPU min MHz:           800.0000
BogoMIPS:              3990.19
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              2048K
NUMA node0 CPU(s):     0,1
