### ISSUE TITLE
After sync, i have null messages

### ISSUE THREAD

**Issue by Percherie** [nerzhul/ownCloud-SMS-App#60]
Hi,

ocsms web work, applics for android have succeful sync my data but in owncloud i have nobody message in http://<my_cloud>/index.php/apps/ocsms/

I use :
owncloud-sms 0.18.2
owncloud 8.4
android 5.0
sansumg S5

**Comment by nerzhul** [comment]
you get nobody message  ? can you be more precise please ? Can you also look at issue template style in README ?

Thanks

**Comment by Percherie** [comment]
No where is this readme ? I read on playstore, app of owncloud and readme.md

I have nobody message, it's similar if it's succeful but a don't have dat

**Comment by nerzhul** [comment]
Could you look at your apache logs and data/owncloud.log ?

**Comment by Percherie** [comment]
i don't acces to my log apache. Now i submit one copie to my log for 00h00

**Comment by nerzhul** [comment]
awaiting you ]

**Comment by nerzhul** [comment]
@Percherie ping ?

**Comment by Percherie** [comment]
Sorry i forget,

After install official application owncloud for android it's work... i test tomorow after delete official application but it's strange

**Comment by nerzhul** [comment]
Oh you are using unofficial application ? It's possible the unofficial doesn't work properly, i don't support it, they get the sources and re-build it, but maybe they have something wrong

**Comment by Percherie** [comment]
it was temporary as a few weeks the official application could no longer display the contents of my cloud. Only unofficial app arrived there.

Since the last update of the official working again

**Comment by nerzhul** [comment]
I close the issue
