### ISSUE TITLE
app doesn't work with oc 8.1.0.3

### ISSUE THREAD

**Issue by dh-connect** [nerzhul/ownCloud-SMS-App#61]
since i upgrade to oc 8.1 the apps doesn't sync anymore: Fehler #9: Unbekannter HTTP-Antwortcode vom Server, on oc 8.0 everything was fine

i'm using oc 8.1.0.3 / oc sms 1.5.0
latest app version on android

**Comment by nerzhul** [comment]
can you give me your apache logs ?

**Comment by dh-connect** [comment]
sorry for false alarm, i could get it to work, it had to do with apache modsecurity module which i had activated

**Comment by nerzhul** [comment]
okay, no problem, thanks for the return :) i close the issue
