### ISSUE TITLE
App crashes on synchronizing

### ISSUE THREAD

**Issue by xn--nding-jua** [nerzhul/ownCloud-SMS-App#62]
Hi,

your app crashes everytime I try to sync. The Android-debug-console says:
Could not find method android.app.Notification$Builder.build, referenced from method fr.nrz.androidlib.notifications.NrzNotification.createNotify

Here the full error-message:
07-15 15:56:41.554  17513-17513/? D/dalvikvm? Late-enabling CheckJNI
07-15 15:56:41.804  17513-17529/fr.unix_experience.owncloud_sms:sync I/dalvikvm? Could not find method android.app.Notification$Builder.build, referenced from method fr.nrz.androidlib.notifications.NrzNotification.createNotify
07-15 15:56:41.804  17513-17529/fr.unix_experience.owncloud_sms:sync W/dalvikvm? VFY: unable to resolve virtual method 139: Landroid/app/Notification$Builder;.build ()Landroid/app/Notification;
07-15 15:56:41.804  17513-17529/fr.unix_experience.owncloud_sms:sync D/dalvikvm? VFY: replacing opcode 0x6e at 0x0025
07-15 15:56:41.814  17513-17529/fr.unix_experience.owncloud_sms:sync W/dalvikvm? threadid=11: thread exiting with uncaught exception (group=0x40ad8228)
07-15 15:56:41.814  17513-17529/fr.unix_experience.owncloud_sms:sync E/AndroidRuntime? FATAL EXCEPTION: SyncAdapterThread-1
    java.lang.NoSuchMethodError: android.app.Notification$Builder.build
            at fr.nrz.androidlib.notifications.NrzNotification.createNotify(NrzNotification.java:56)
            at fr.unix_experience.owncloud_sms.notifications.OCSMSNotificationManager.createNotificationIfPossible(OCSMSNotificationManager.java:61)
            at fr.unix_experience.owncloud_sms.notifications.OCSMSNotificationManager.setSyncProcessMsg(OCSMSNotificationManager.java:33)
            at fr.unix_experience.owncloud_sms.sync_adapters.SmsSyncAdapter.onPerformSync(SmsSyncAdapter.java:56)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)

If I compile the app without the NrzNotification-code it synchronizes the sms with owncloud without a problem. I'm using Android 4.0.3 with three devices. On all the error appears.

kind regards,
Chris

**Comment by nerzhul** [comment]
It's not a bug, it's a missing dependancy you fix. Official app is present on google play store including all the proper packaging :). I will add a link to the dep in the README.md

**Comment by nerzhul** [comment]
This is already said there : https://github.com/nerzhul/ownCloud-SMS-App/wiki
