### ISSUE TITLE
Provide infos about used versions of nrz-androidlib and Owncloud-Android-Library

### ISSUE THREAD

**Issue by RealRancor** [nerzhul/ownCloud-SMS-App#63]
Hi,

i'm currently updating the app on f-droid and stumbled over the problem that you don't specify which versions of the nrz-androidlib and Owncloud-Android-Library you're using / testing against. Could you add this infos to the readme or some other files? Thanks

**Comment by nerzhul** [comment]
@RealRancor thanks for the porting to F-Droid. nrz-androidlib is the last version. For OwnCloud-Android-Library it's the version 1.0

**Comment by DJaeger** [comment]
How about building instructions in the README?

**Comment by RealRancor** [comment]
@nerzhul Currently updating the app on f-droid. Short question, seems OwnCloud-Android-Library is 0.9.9 https://github.com/owncloud/android-library/releases Where are you getting 1.0 from?

**Comment by nerzhul** [comment]
@RealRancor thanks for the tip. I will look at the used lib to upgrade it to latest stable version. Maybe tomorrow

**Comment by thfree** [comment]
Fuck it, I only on the third day, was able to collect.
