### ISSUE TITLE
Application stopped working when receiving message without registered account

### ISSUE THREAD

**Issue by agilob** [nerzhul/ownCloud-SMS-App#64]
1. install owncould-sms-app
2. ignore registration
3. receive sms
4. application crashes

**Comment by nerzhul** [comment]
@agilob thanks for the report. Application is at 0.18.5, please use 0.18.5 and give me the logcat logs to fix this issue.

**Comment by nerzhul** [comment]
Fixed: cc14488a88ecbd84e73dc73c209812fd03f9f297
