### ISSUE TITLE
Heavy data usage?

### ISSUE THREAD

**Issue by jas4711** [nerzhul/ownCloud-SMS-App#66]
I installed ocsms 0.18.5 from fdroid and using it with an ownCloud 8.1 instance with latest ocsms app (from git, pulled early August 2015).  I'm seeing a lot of data usage from the app.  It seems to use around 20MB per day.  Is this to be expected?  Is it sending all of SMSs over and over?  I can imagine the initial push to consume some bandwidth, but after that it seems bandwidth usage should be limited to handshake noise and sending new SMSs.

**Comment by nerzhul** [comment]
hi @jas4711 , it depends on how many messages do you have on your phone. Please note there is two sync: the full differential sync and the incremental sync, you can disable the full differential sync or change the interval directly in the settings. By default it's 15 mins, but you may want to have a larger interval to reduce data usage

**Comment by nyxxo** [comment]
Hi @nerzhul,

where can I change the sync settings (differential/incremental)? I only see the sync frequency as well as the settings for syning on WiFi, LTE, asf.

I set the syncing interval to 24hours and to wifi only, but according to my phone it took already 100mB of my quota and I'm getting the "synchronizing" message several times a day. Is it possible that the app ignores my settings?

**Comment by nerzhul** [comment]
@nyxxo did you disable push on receive too ?

**Comment by nyxxo** [comment]
@nerzhul 

I did. The only checked box is "synchronize in wi-fi".

**Comment by nerzhul** [comment]
hi @nyxxo i found a bug fixed this evening which make the interval of sync not being used properly. The default was used every time. I will release soon.
I also add a bulk mode with a message limit per sync to prevent heavy load on android + data
