### ISSUE TITLE
Multiple Android device sync

### ISSUE THREAD

**Issue by julamulo** [nerzhul/ownCloud-SMS-App#67]
Trying to sync my SMS from phone to owncloud then to tablet
ownCloud SMS installed on my phone and tablet, sync is ok
ownCloud server show my SMS from my phone => ok
tablet with SMS AOSP app doesn't show any SMS, I tried also with Google Messenger but no luck

Should multiple Android device sync work ?

**Comment by nerzhul** [comment]
@julamulo did you try to import SMS from the server to your tablet ?

**Comment by julamulo** [comment]
Not sure i'm doing it right.
I have installed ownCloud SMS on the tablet and launched synchronisation with owncloud server. I don't know if it's the way to import

**Comment by nerzhul** [comment]
at this moment it's not possible to import SMS, only to export them. I'm working it on atm, but the feature will be a SMS restauration function

**Comment by julamulo** [comment]
Ok thanks for our answer. Your app is super

**Comment by nerzhul** [comment]
@julamulo thanks, but it could be better than that :) I just need some time, or patches
