### ISSUE TITLE
Can't use self signed certificate

### ISSUE THREAD

**Issue by skjnldsv** [nerzhul/ownCloud-SMS-App#70]
Hi, my owncloud installation is set on a custom port with ssl and a self-signed cert.
I can't login properly with all thos settings defined.

If I set my port like user@host:port, I always get an error.
Thanks for your promising app, it looks pretty awesome!

**Comment by nerzhul** [comment]
Hello, thanks for your usage
Did you tried to set host:port in the host field ?

**Comment by skjnldsv** [comment]
Hi!
Yes I did and I get an unknow error. :/
Do you want me to post a logcat?

Regards.

**Comment by nerzhul** [comment]
Could be interesting :)

**Comment by skjnldsv** [comment]
I can't get anything from it! Any line from the process.
I'm using FDroid version, could this be the problem?
I don't and can't have gapps on my phone, so no play version for me! :/

**Comment by nerzhul** [comment]
i think there is a problem in URI parsing.

**Comment by skjnldsv** [comment]
If I could be any help tell me! :)

**Comment by skjnldsv** [comment]
Hi, any news?

**Comment by brandonk10** [comment]
This may not be a problem with the port.  I was having the same issue, and it turned out to be the self-signed cert.  Unlike owncloud, I never got a prompt to accept the certificate.  Looking at the code, there is a certificate store that the app holds, but I don't think there is anything pushing the self-signed cert into that store.  I solved this with a quick and dirty custom build of the app - I added text box that took a path to the cert on the account add screen, and added the cert into the store(NetworkUtils) before logging in.  Once I got this going, the custom port worked just fine.

**Comment by nerzhul** [comment]
hi @brandonk10 for the self signed certificate official app don't verify the validity of the certificate because the used owncloud client doesn't permit to accept it on this build. If you use f-droid or other APK built from users and don't supported by us the certificate check will not work and break the thing.

**Comment by brandonk10** [comment]
I faced same issue building myself from GIT.  I couldn't find any place where validation was turned off in code, and the OC client library v1 seems to validate certs by default.  In any case, custom ports work fine once the app-local cert store is updated, without changing anything else in code.  Maybe you have built with a different source for OC library v1.

**Comment by skjnldsv** [comment]
So what solutions do we have?
Does the play store app works with self signed cert?

**Comment by DTux69** [comment]
Hi,

same problem, catlog say http error  400

11-01 18:48:20.004 E/NativeCrypto(21678): ssl=0x61557110 cert_verify_callback x509_store_ctx=0x631ff940 arg=0x0
11-01 18:48:20.004 E/NativeCrypto(21678): ssl=0x61557110 cert_verify_callback calling verifyCertificateChain authMethod=RSA
11-01 18:48:20.309 E/OwnCloudAuthenticator(21678): Failed response while getting user information 
11-01 18:48:20.309 E/OwnCloudAuthenticator(21678): *** status code: 400 ; response message: <!DOCTYPE html>
11-01 18:48:20.309 E/OwnCloudAuthenticator(21678): 
11-01 18:48:20.309 E/OwnCloudAuthenticator(21678): 
11-01 18:48:20.309 E/OwnCloudAuthenticator(21678):

**Comment by brandonk10** [comment]
@nerzhul -

If you look at the android library test client, it comes with code to override the default behavior to support self-signed certificates.  That seems to be the easiest way to address this, though it will not handle "local" CA-signed certs.

I suspect the main OC android client is handling cert errors by checking RemoteOperationResult for certificate errors, prompting to accept, calling NetworkUtils.addCertToKnownServersStore, followed by a retry of the failed client operation.  This would be a more involved change.

**Comment by derritter88** [comment]
I am also having the same troubles with my own signed certificate.

**Comment by jos1264** [comment]
hi guys,

for self signed certificate just export it (.cer format) and install on your android phone. after this it should work

**Comment by skjnldsv** [comment]
@jos1264 Thank you sooo much!!

**Comment by nerzhul** [comment]
Will look at a smoother SSL certificate checking, the used ownCloud Android lib is not very good on this

**Comment by ioiobzit** [comment]
Hello, it would be great to have this functionality! This issue is what is stopping me to use this awesome project!

All the best.

**Comment by nerzhul** [comment]
@ioiobzit it works with google play store app (i have a self signed certificate on my test server). But as i remember doesn't work on F-Droid app

**Comment by bhuvi8** [comment]
I installed the app from F-Droid repo and the app didn't work with my self signed certificate.
As a workaround, I installed CAdroid app from F-Droid repo to import my self-signed certificate to android trusted store and the sync now works.

**Comment by nerzhul** [comment]
@bhuvi8 it's the only solution for F-Droid atm because it's a limitation in the owncloudClient library

**Comment by cengbrecht** [comment]
If its just an issue with self signed, use letsencrypt. Lots of tutorials telling you how.

**Comment by kbaegis** [comment]
So I don't use a public domain, therefore letsencrypt isn't a valid solution for me. Also using the certificate store for public certificates annoyingly requires a pin to be entered every time an android phone powers down (constantly).  Legitimate support for self-signed certificates would be greatly appreciated.

**Comment by nerzhul** [comment]
It's supported with the official version on play store. F-Droid version is not ours.
