### ISSUE TITLE
Phone Number / Name assignment with country codes

### ISSUE THREAD

**Issue by nyxxo** [nerzhul/ownCloud-SMS-App#71]
Hi,

I'm using your app since today and the sync worked perfectly. But now I have the problem that the Webfrontend does not recognize the contact if as country code was given for the phone number (XOR, either in the sms oder in the contact - if both have it is of course linked).

Example:
Contact: Mr. Phone: 0199 99999
SMS: +49 199 999999

It looks like you are doing a simple comparison, whether the numbers are identical. If they are not, a new entry with just the number is created. 

Solution:
It should be quite easy to link the two - as soon as there is an "+" in the phone number, ignore the first two digits of the SMS number and ignore the first digit of the contact number to find a match.

Thanks in advance!

**Comment by nerzhul** [comment]
hi @nyxxo the problem is that many countries use different phone schemes, we have a mapper for phones, maybe there is something wrong for you and you can help ? :)

**Comment by nyxxo** [comment]
Hi @nerzhul,

If you don't mind to hint me to the right place I will see what I can do!

**Comment by nerzhul** [comment]
@nyxxo go to nerzhul/ocsms repository instead of this repository for this question, we have a parser for phone number, if you see an issue on it, don't hesitate to do a PR
