### ISSUE TITLE
Sync error message although sync interval is disabled

### ISSUE THREAD

**Issue by keynlotepan** [nerzhul/ownCloud-SMS-App#72]
My current use case is to sync with my owncloud server on my pc. Because this pc is not always turned on (and I am not always in my home network) I set sync interval of owncloud-SMS-App disabled ("Nie" (=never) in my German version). Until version f-droid 0.18.2 this approach worked well (on my CM11 and my wife's Android 5), but current version 0.18.5 produces server connect error messages.
I understand that ownCloud-SMS tries to sync receiving a message and therefore an error message is reasonable when the server is turned off. But I would appreciate if there was an operating mode for those who do not operate a permanent available server and do not want to have error messages.

Possible solutions:
* error messages only on connect errors during recurring syncs (as in vsn. 0.18.2)
* better: connect error messages can be suppressed
* much better: only permanently recurring occurrences of errors (for a configurable time span, e.g. one week or zero (for a behaviour like now)) will be reported ("no successful sync for xyz days")

I hope one of the listed possible solutions is feasible. Last but not least thanks for this app.

**Comment by nerzhul** [comment]
@keynlotepan outdated version. Please use 0.19.0 or 0.19.1, this is fixed.

**Comment by keynlotepan** [comment]
Thanks for this information. I do not have access to the version mentioned above, since the latest one on F-Droid is 0.18.5 and we operate our devices without Google apps/account. Will further versions be published on F-Droid or do I have to compile it by myself?

**Comment by nerzhul** [comment]
@keynlotepan i think the F-Droid maintainer should update its build process, i didn't maintain it myself
