### ISSUE TITLE
0.19 Costantly crashes on Android 5.0.1

### ISSUE THREAD

**Issue by delumerlino** [nerzhul/ownCloud-SMS-App#73]
Hi, the app was great with 0.18.5.
Now with 0.19 I receive "owncloud sms has stopped working" when loading the SMS app.
When forcing syncing, it hangs on "sync in progress".
I push 1000 sms per sync.
No messages on OC server.

Thank you

**Comment by nerzhul** [comment]
hi @delumerlino can you use logcat to help me find the problem ? Thanks

**Comment by delumerlino** [comment]
Sure, here it is.
Thank you!
[alogcat.2015-12-01-14-47-56+0100.txt](https://github.com/nerzhul/ownCloud-SMS-App/files/48555/alogcat.2015-12-01-14-47-56.0100.txt)

**Comment by nerzhul** [comment]
@delumerlino thanks but your backtrace isn't precise, fetcher.fetchAllMessages(smsList); is the call mentionned by your stacktrace but if you can have more precise backtrace it could be good for me to debug, there are many lines of code behind fetcher.fetchAllMessages(smsList);

**Comment by delumerlino** [comment]
I have filtered only for ocsms, I will send you more accurate log...

2015-12-01 14:55 GMT+01:00 nerzhul <notifications@github.com>:

> @delumerlino <https://github.com/delumerlino> thanks but your backtrace
> isn't precise, fetcher.fetchAllMessages(smsList); is the call mentionned by
> your stacktrace but if you can have more precise backtrace it could be good
> for me to debug, there are many lines of code behind
> fetcher.fetchAllMessages(smsList);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nerzhul/ownCloud-SMS-App/issues/73#issuecomment-160976379>
> .
>



-- 
--------------------------------------------------------------------------
*P *Prima di stampare, pensa all'ambiente ** Think about the environment

**Comment by nerzhul** [comment]
if the current backtrace is not precise we should wait next backtrace, else i will review everything but crash could occur for many reasons on android. It's strange that this crash doesn't happen with a manual sync but i also see it rarely. I will plug my phone on Android Studio this evening and see if android will report the crash.

**Comment by delumerlino** [comment]
here is a more accurate log:
[alogcat.2015-12-01-14-57-38+0100.txt](https://github.com/nerzhul/ownCloud-SMS-App/files/48569/alogcat.2015-12-01-14-57-38.0100.txt)

TY!

**Comment by nerzhul** [comment]
Thanks i found where the crash occurs ! this backtrace permit to see a problem... i will patch it and release a bugfix release this evening

**Comment by delumerlino** [comment]
Great! Thank you lots!

2015-12-01 15:07 GMT+01:00 nerzhul <notifications@github.com>:

> Thanks i found where the crash occurs ! this backtrace permit to see a
> problem... i will patch it and release a bugfix release this evening
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nerzhul/ownCloud-SMS-App/issues/73#issuecomment-160978915>
> .
>



-- 
--------------------------------------------------------------------------
*P *Prima di stampare, pensa all'ambiente ** Think about the environment

**Comment by nerzhul** [comment]
No, you, i thank you for your investigation :D

**Comment by delumerlino** [comment]
I am very glad to be part of the project! :)

2015-12-01 15:13 GMT+01:00 nerzhul <notifications@github.com>:

> No, you, i thank you for your investigation :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nerzhul/ownCloud-SMS-App/issues/73#issuecomment-160980181>
> .
>



-- 
--------------------------------------------------------------------------
*P *Prima di stampare, pensa all'ambiente ** Think about the environment

**Comment by delumerlino** [comment]
Thanks a lot, the update work like a charm! :+1:
