### ISSUE TITLE
fatal error #13 on automatic sync

### ISSUE THREAD

**Issue by supersn0b** [nerzhul/ownCloud-SMS-App#75]
Hi,

I keep getting 'fatal error #13' every time I switch on my wifi/data connection.
However, when I sync manually, everything works fine.
What could be the reason for this?

Here my environment:
Gentoo Linux/Owncloud 8.2.1
Android 4.2/owncloud-sms 0.18.5 from f-droid

**Comment by nerzhul** [comment]
hi @supersn0b the error #13 significate that he periodic sync is not able to connect to your instance, perhaps because connection was aborted. The error triggers when exactly ?

**Comment by supersn0b** [comment]
the error triggers every time when I connect to wifi/dataconnection. and it doesn't matter whether I have sync enabled globally or not. moreover, it doesn't matter whether I set the sync frequency in the app to 'never' or not, the error shows up always.

**Comment by nerzhul** [comment]
ok, i need to look at the code when you switch. owncloud sms synchronise differentially SMS when you are connecting to a access point on which you permit sync

**Comment by nerzhul** [comment]
@supersn0b i look at this

**Comment by supersn0b** [comment]
@nerzhul great! let me know when you need more information or some testing from my side :-)

**Comment by nerzhul** [comment]
the bug here is we trigger a sync when changing access point whereas you didn't enable it, right ?

**Comment by supersn0b** [comment]
I think so. The sync setting 'never' is never respected ;-)

**Comment by nerzhul** [comment]
@supersn0b i looked at the code and i see the connectivity manager is called too verify if we can sync... i need to look a little bit more

**Comment by supersn0b** [comment]
works
