### ISSUE TITLE
contact list, "Server doesn't support this feature."

### ISSUE THREAD

**Issue by jstebbins** [nerzhul/ownCloud-SMS-App#76]
Owncloud 8.2 from owncloud Open Build Service
ownCloud SMS web app 1.5.0 from owncloud app store
ownCloud SMS 0.19.2 from google play store

Choose Account and under Contact list and Contact informations it says "Server doesn't support this feature".

I have CardDAV-Sync installed and have all contacts on my owncloud instance.  Am I doing something wrong or missing some dependency?

**Comment by nerzhul** [comment]
Is this in Remote account section ?
If yes i released accidentally an unfinished feature , and i will remove it soon from release or finish to  develop both client & server

**Comment by jstebbins** [comment]
Yes, Remote account.  Thanks for the answer.
