### ISSUE TITLE
Option to Limit SMS shown per page

### ISSUE THREAD

**Issue by p91** [nerzhul/ownCloud-SMS-App#77]
Hi,

first of all, thank you very much for this app.
Unfortunately, I cannot use it at the moment as it always crashes my firefox.
I suspect this is due to the amount of SMS per conversation I have.
Most of my conversations work fine in ownCloud-SMS-App (meaning i can sync and view them in ownCoud) but by longer conversations (>3000 SMS) can only be synced and not viewed without firefox freezing and, if I do not stop the scripts running, crashing.

Could the please have an options to like display the last x SMS in the conversation? Let x=500 as the default and if someone needs older SMS he can just click "next page" or scroll up and the next messages can be loaded in the background ore something.

With best regards, 

p91

**Comment by p91** [comment]
Okay, I have to correct myself. it does not actually crash firefox, that was a addon I guess (if I just use a firefox without any addons it will display the "the script seems to have stopped dialog" and if I let it go in the page will display all 3000 SMS.). I would still prefer a option to only display the first 500 or so.

**Comment by nerzhul** [comment]
hi @p91 can you send this suggestion on the correct github repo ?

https://github.com/nerzhul/ocsms

**Comment by p91** [comment]
Ops, sorry :( 

I will post it at the right github. Sorry for the inconvenience!
