### ISSUE TITLE
Marshmallow Support

### ISSUE THREAD

**Issue by computerfr33k** [nerzhul/ownCloud-SMS-App#78]
Would this application be able to support marshmallow by just incrementing the max sdk version? Or does it currently have incompatibilities with libraries or something?

**Comment by nerzhul** [comment]
@computerfr33k what is the android version ? i upgraded AndroidManifest to support 6.0 and pushed it to google play store last week :)

**Comment by computerfr33k** [comment]
I guess you're right. I thought that the max sdk version was set incorrectly as it is still at 22, but iguess doing some googling showed that it isnt really used anymore. Plus, I've been looking for it on F-Droid and noticed is hasn't been updated in a while.
