### ISSUE TITLE
Provide new version for F-Droid

### ISSUE THREAD

**Issue by stefan-niedermann** [nerzhul/ownCloud-SMS-App#86]
The current version is outdated (0.18.x)

> We don't have the current version of this app. (Check mode: Tags) (Auto-update mode: None)
The current (recommended) version is 0.20.0 (version code 33).

**Comment by nerzhul** [comment]
I don't provide any F-Droid builds, you should try to build it yourself. I'm working slowly on rewriting the HTTP handling to remove the owncloud library problems but it's not finished yet.
