### ISSUE TITLE
Missing root project

### ISSUE THREAD

**Issue by krt16s** [nerzhul/ownCloud-SMS-App#87]
The `buildscript` portion of the gradle setup is missing. It looks like this is a multiproject setup, so you should have a `../settings.gradle` and `../build.gradle` while the code you posted most likely belongs in a subfolder like `../app/`.

**Comment by thfree** [comment]
The project is going, but a lot of swearing and dependencies confusion. [http://thfree.ru:83/build/outputs/apk/outputs/lint-results.html](url)

**Comment by nerzhul** [comment]
@krt16s working is in progress to have a more interesting build.
