### ISSUE TITLE
Error #13

### ISSUE THREAD

**Issue by krisken** [nerzhul/ownCloud-SMS-App#88]
Server

```
ownCloud version: ownCloud 8.2.2
PHP version: 5.5.9
HTTPd server: Apache
HTTPS: don't use it (at this momnet)
```

Client

```
Android version: 5.0.1
Phone: Huawei P8
ownCloud SMS app version: 0.20.0
```

Content of /owncloud/data/owncloud.log

reqId":"WNezTNHiZm1VnVehdSC7","remoteAddr":"","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM m$
{"reqId":"WNezTNHiZm1VnVehdSC7","remoteAddr":"","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON$
{"reqId":"WNezTNHiZm1VnVehdSC7","remoteAddr":"","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/setup\/mysql.php#45","level":3,"time"$
{"reqId":"WNezTNHiZm1VnVehdSC7","remoteAddr":"","app":"PHP","message":"fopen(\/var\/www\/owncloud\/config\/config.php): failed to open stream: No such file or director$
{"reqId":"1v7T\/pjGtKOyrkz6ehTk","remoteAddr":"94.110.157.29","app":"core","message":"Login failed: 'admin' (Remote IP: '94.110.157.29')","level":2,"time":"2016-02-20T$
{"reqId":"\/YloX8FA\/P7inTieh0YM","remoteAddr":"94.110.157.29","app":"core","message":"Login failed: 'admin' (Remote IP: '94.110.157.29')","level":2,"time":"2016-02-20$
{"reqId":"6QG3uczZfSZWIFIHYbRD","remoteAddr":"94.110.157.29","app":"core","message":"Login failed: 'admin' (Remote IP: '94.110.157.29')","level":2,"time":"2016-02-20T1$
{"reqId":"SyfiRYTZZ\/kvi\/1Mp+wS","remoteAddr":"94.110.157.29","app":"core","message":"Login failed: 'admin' (Remote IP: '94.110.157.29')","level":2,"time":"2016-02-20$
{"reqId":"xiwoQrkNYHsftqMDD6T5","remoteAddr":"94.110.157.29","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var$
{"reqId":"8Y0jiWhCMAFBa5AuJAwH","remoteAddr":"178.50.74.90","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\$
{"reqId":"abGgWF8IEVUlFJnt00Gk","remoteAddr":"178.50.74.90","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\$
{"reqId":"YKyJThcmwUwKQRKlZTwv","remoteAddr":"94.110.157.29","app":"core","message":"Login failed: 'admin' (Remote IP: '94.110.157.29')","level":2,"time":"2016-02-20T1$
{"reqId":"CdHRBG9jMTJoK9czQOcg","remoteAddr":"94.110.157.29","app":"core","message":"Login failed: 'admin' (Remote IP: '94.110.157.29')","level":2,"time":"2016-02-20T1$
{"reqId":"4IFo0OJZ7\/PJhFHEVLCN","remoteAddr":"178.50.74.90","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var$
{"reqId":"tBlZEcrXLVRywduDD\/XY","remoteAddr":"178.50.74.90","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var$
{"reqId":"SpKsPJCx+lt8Pw0frVrL","remoteAddr":"178.50.74.90","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\$
{"reqId":"YbW6PHVIlQhoHhVSMx1W","remoteAddr":"94.110.157.29","app":"PHP","message":"call_user_func() expects parameter 1 to be a valid callback, class 'OCA\OcSms\Db\$
{"reqId":"yJWZFbdP5b3s5ZuiDSFx","remoteAddr":"94.110.157.29","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\DBAL\\Exception\\DriverException\",\"$
{"reqId":"rY5FxLvCWITEzECVpmGz","remoteAddr":"94.110.157.29","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\DBAL\\Exception\\DriverException\",\"$
{"reqId":"Mn9iq5cZf4jhbG3hiv+7","remoteAddr":"213.118.187.202","app":"core","message":"Login failed: 'krisken' (Remote IP: '213.118.187.202')","level":2,"time":"2016-0$
{"reqId":"Mn9iq5cZf4jhbG3hiv+7","remoteAddr":"213.118.187.202","app":"core","message":"Login failed: 'krisken' (Remote IP: '213.118.187.202')","level":2,"time":"2016-0$
{"reqId":"lXUzG4\/FaewBvVtYD1de","remoteAddr":"213.118.187.202","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/$
{"reqId":"7X\/5cRBbh9eRlLd2XIcs","remoteAddr":"213.118.187.202","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/$
{"reqId":"F2eqB1ttANJE5qZCY+Te","remoteAddr":"213.118.187.202","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/v$
{"reqId":"QFmabOWi3TxA9ZFvPgNi","remoteAddr":"213.118.187.202","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/v$
{"reqId":"72lgqG0OJhT08qeHJM3w","remoteAddr":"213.118.187.202","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/v$
{"reqId":"yQVgV9TC6skixn5TWSfs","remoteAddr":"213.118.187.202","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/v$
{"reqId":"MRk61KsNOiKjWc6lkVzT","remoteAddr":"213.118.187.202","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/v$
{"reqId":"PilQxTfBa0zrBvJIJsKT","remoteAddr":"213.118.187.202","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/v$
{"reqId":"IkhtF7zUiwyGuP9gliuH","remoteAddr":"213.118.187.202","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/v$
{"reqId":"4nz8ROaaJWaaDqZK0Oy3","remoteAddr":"213.118.187.202","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/v$
{"reqId":"zWv+K4T7bAN\/bFEIMMxz","remoteAddr":"213.118.187.202","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/$
{"reqId":"73JRBb61STWWXKeXE\/n8","remoteAddr":"213.118.187.202","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/$
{"reqId":"cAQIOYPfKK6Rcfqe3UHx","remoteAddr":"213.118.187.202","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/v$
{"reqId":"\/hyBOp34\/vjt6xwEjCbX","remoteAddr":"213.118.187.202","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \$
{"reqId":"15hszTx+J2ZFDwhQsX\/i","remoteAddr":"213.118.187.202","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/$

I installed OwnCloud SMS app on my Huawei P8 cell phone and i always get a error 13.  I get a notification "sync process - sync in process" and after a few minutes later i get the error "Error #13".
At this moment I also use the android app and the windows app of owncloud and this work fine, so i suppose there are no troubles with my server?

Does Owncloud SMS create a map on the Owncloud server?  If so : what is the name of that map?  If it isn't : is it possible to choose a map?

Best regards
Kris

**Comment by nerzhul** [comment]
It seems you have a problem in your owncloud DB driver with callback. Don't know why atm but it's not a ocsms problem i think. Will look at this

**Comment by krisken** [comment]
Hello,

I can give you access to my OwnCloud if you want to?

Kris

Op 21/02/2016 om 10:18 schreef nerzhul:

**Comment by nerzhul** [comment]
@krisken do you have access to owncloud SMS panel on web interface ?

**Comment by krisken** [comment]
I sure do have access but i can't change a lot?
When i go to http://my.ip.address/index.php/apps/ocsms/ i see the text 
"Please choose a conversation on the left menu".
I don't see anything on the left, just a small gear wheel at the 
left-bottom.  When i click on it:
- Max messages on tab loading
- Country code
- Notification settings

That's it.
Is this OK?

Kris

Op 22/02/2016 om 10:25 schreef nerzhul:

**Comment by nerzhul** [comment]
@krisken this is okay for me.
Can you upgrade to last owncloud sms app server side and client side ?

**Comment by nerzhul** [comment]
ping @krisken

**Comment by nerzhul** [comment]
user timeout
