### ISSUE TITLE
does not create an account after compilation

### ISSUE THREAD

**Issue by thfree** [nerzhul/ownCloud-SMS-App#89]
0.20.0 - does not create an account after compilation. Drop from a mistake.

Android 5.1.1 (Xperia Z1 Compact)
CyanogenMod 12.1

**Comment by thfree** [comment]
03-05 13:43:26.487 E/AndroidRuntime(6949): FATAL EXCEPTION: main
03-05 13:43:26.487 E/AndroidRuntime(6949): Process: fr.unix_experience.owncloud_sms, PID: 6949
03-05 13:43:26.487 E/AndroidRuntime(6949): java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.unix_experience.owncloud_sms/fr.unix_experience.owncloud_sms.activities.LoginActivity}: android.view.InflateException: Binary XML file line #123: Error inflating class com.dd.processbutton.iml.ActionProcessButton
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.os.Looper.loop(Looper.java:135)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at java.lang.reflect.Method.invoke(Native Method)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at java.lang.reflect.Method.invoke(Method.java:372)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
03-05 13:43:26.487 E/AndroidRuntime(6949): Caused by: android.view.InflateException: Binary XML file line #123: Error inflating class com.dd.processbutton.iml.ActionProcessButton
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at fr.unix_experience.owncloud_sms.activities.LoginActivity.onCreate(LoginActivity.java:74)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.app.Activity.performCreate(Activity.java:5990)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	... 10 more
03-05 13:43:26.487 E/AndroidRuntime(6949): Caused by: java.lang.reflect.InvocationTargetException
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at java.lang.reflect.Constructor.newInstance(Native Method)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	... 23 more
03-05 13:43:26.487 E/AndroidRuntime(6949): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/dd/processbutton/R$styleable;
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at com.dd.processbutton.FlatButton.initAttributes(FlatButton.java:45)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at com.dd.processbutton.FlatButton.init(FlatButton.java:38)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at com.dd.processbutton.FlatButton.<init>(FlatButton.java:27)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at com.dd.processbutton.ProcessButton.<init>(ProcessButton.java:31)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at com.dd.processbutton.iml.ActionProcessButton.<init>(ActionProcessButton.java:64)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	... 26 more
03-05 13:43:26.487 E/AndroidRuntime(6949): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dd.processbutton.R$styleable" on path: DexPathList[[zip file "/data/app/fr.unix_experience.owncloud_sms-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
03-05 13:43:26.487 E/AndroidRuntime(6949): 	... 31 more
03-05 13:43:26.487 E/AndroidRuntime(6949): 	Suppressed: java.lang.ClassNotFoundException: com.dd.processbutton.R$styleable
03-05 13:43:26.487 E/AndroidRuntime(6949): 		at java.lang.Class.classForName(Native Method)
03-05 13:43:26.487 E/AndroidRuntime(6949): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
03-05 13:43:26.487 E/AndroidRuntime(6949): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
03-05 13:43:26.487 E/AndroidRuntime(6949): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-05 13:43:26.487 E/AndroidRuntime(6949): 		... 32 more
03-05 13:43:26.487 E/AndroidRuntime(6949): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by nerzhul** [comment]
I think a library is missing

**Comment by thfree** [comment]
`git clone https://github.com/dmytrodanylyk/android-process-button.git`
~ Build - copying library - build app - starting app

**Comment by nerzhul** [comment]
what is this android-process-button ? You didn't use gradle ?

**Comment by thfree** [comment]
Easier buy, but I do not have "google play".
Therefore, I try to compile.
... I use Gradle.

My edits to assemble.
.../progect
add /owncloudAndroidLibrary
add /src/main/java/nrz
add /settings.gradle 
`':owncloudAndroidLibrary'
`

edit /build.gradle
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
    }
}
apply plugin: 'com.android.application'
...
dependencies {
...
delete  compile project(':nrzandroidlib')                                                                                                                        
...
}
```

gradle assemble

**Comment by nerzhul** [comment]
This issue is obsolete
