### ISSUE TITLE
jitpack

### ISSUE THREAD

**Issue by est31** [nerzhul/ownCloud-SMS-App#98]
F-droid only allows whitelisted maven repos. `oss.sonatype.org` is not one of those AFAIK. Currently the reason for the f-droid build to not update to the most recent version is this issue (and #97).

Jitpack is a whitelisted repo. It provides a guide how to set up `build.gradle` with the needed libraries:

* https://jitpack.io/#owncloud/android-library/oc-android-library-0.9.10
* https://jitpack.io/#nerzhul/nrz-androidlib/42a36f7c97

I can try to make a patch if desired :)

**Comment by nerzhul** [comment]
@est31 if you can, could be good :)

**Comment by est31** [comment]
Fixed by 8805869542aee6befaf6fc57ca1454bc6b1d1a6a
